/**
 * index-browser
 *
 * Responsabilidad: Modulo interno del sistema.
 * Limites: Mantener contrato y comportamiento observable del modulo.
 */

/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.PerfilAlumnoScalarFieldEnum = {
  id: 'id',
  periodoId: 'periodoId',
  alumnoId: 'alumnoId',
  matricula: 'matricula',
  nombreCompleto: 'nombreCompleto',
  grupo: 'grupo',
  docenteId: 'docenteId',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ResultadoAlumnoScalarFieldEnum = {
  id: 'id',
  periodoId: 'periodoId',
  docenteId: 'docenteId',
  alumnoId: 'alumnoId',
  examenGeneradoId: 'examenGeneradoId',
  matricula: 'matricula',
  nombreCompleto: 'nombreCompleto',
  grupo: 'grupo',
  folio: 'folio',
  tipoExamen: 'tipoExamen',
  totalReactivos: 'totalReactivos',
  aciertos: 'aciertos',
  calificacionExamenFinalTexto: 'calificacionExamenFinalTexto',
  calificacionParcialTexto: 'calificacionParcialTexto',
  calificacionGlobalTexto: 'calificacionGlobalTexto',
  evaluacionContinuaTexto: 'evaluacionContinuaTexto',
  proyectoTexto: 'proyectoTexto',
  politicaId: 'politicaId',
  versionPolitica: 'versionPolitica',
  componentesExamen: 'componentesExamen',
  bloqueContinuaDecimal: 'bloqueContinuaDecimal',
  bloqueExamenesDecimal: 'bloqueExamenesDecimal',
  finalDecimal: 'finalDecimal',
  finalRedondeada: 'finalRedondeada',
  respuestasDetectadas: 'respuestasDetectadas',
  comparativaRespuestas: 'comparativaRespuestas',
  omrCapturas: 'omrCapturas',
  omrAuditoria: 'omrAuditoria',
  banderas: 'banderas',
  pdfComprimidoBase64: 'pdfComprimidoBase64',
  publicadoEn: 'publicadoEn',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MateriaAlumnoScalarFieldEnum = {
  id: 'id',
  periodoId: 'periodoId',
  alumnoId: 'alumnoId',
  materiaId: 'materiaId',
  nombre: 'nombre',
  docente: 'docente',
  estado: 'estado',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AgendaAlumnoScalarFieldEnum = {
  id: 'id',
  periodoId: 'periodoId',
  alumnoId: 'alumnoId',
  agendaId: 'agendaId',
  titulo: 'titulo',
  descripcion: 'descripcion',
  fecha: 'fecha',
  tipo: 'tipo',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AvisoAlumnoScalarFieldEnum = {
  id: 'id',
  periodoId: 'periodoId',
  alumnoId: 'alumnoId',
  avisoId: 'avisoId',
  titulo: 'titulo',
  mensaje: 'mensaje',
  severidad: 'severidad',
  publicadoEn: 'publicadoEn',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.HistorialAlumnoScalarFieldEnum = {
  id: 'id',
  periodoId: 'periodoId',
  alumnoId: 'alumnoId',
  historialId: 'historialId',
  folio: 'folio',
  tipoExamen: 'tipoExamen',
  calificacionTexto: 'calificacionTexto',
  aciertos: 'aciertos',
  totalReactivos: 'totalReactivos',
  fecha: 'fecha',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CodigoAccesoScalarFieldEnum = {
  id: 'id',
  periodoId: 'periodoId',
  codigo: 'codigo',
  expiraEn: 'expiraEn',
  usado: 'usado',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EventoUsoAlumnoScalarFieldEnum = {
  id: 'id',
  periodoId: 'periodoId',
  alumnoId: 'alumnoId',
  sessionId: 'sessionId',
  pantalla: 'pantalla',
  accion: 'accion',
  exito: 'exito',
  duracionMs: 'duracionMs',
  meta: 'meta',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SesionAlumnoScalarFieldEnum = {
  id: 'id',
  periodoId: 'periodoId',
  alumnoId: 'alumnoId',
  tokenHash: 'tokenHash',
  expiraEn: 'expiraEn',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SolicitudRevisionScalarFieldEnum = {
  id: 'id',
  externoId: 'externoId',
  periodoId: 'periodoId',
  docenteId: 'docenteId',
  alumnoId: 'alumnoId',
  examenGeneradoId: 'examenGeneradoId',
  folio: 'folio',
  numeroPregunta: 'numeroPregunta',
  comentario: 'comentario',
  estado: 'estado',
  solicitadoEn: 'solicitadoEn',
  atendidoEn: 'atendidoEn',
  respuestaDocente: 'respuestaDocente',
  firmaDocente: 'firmaDocente',
  firmadoEn: 'firmadoEn',
  cerradoEn: 'cerradoEn',
  conformidadAlumno: 'conformidadAlumno',
  conformidadActualizadaEn: 'conformidadActualizadaEn',
  origen: 'origen',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PaqueteSyncDocenteScalarFieldEnum = {
  id: 'id',
  docenteId: 'docenteId',
  paqueteBase64: 'paqueteBase64',
  checksumSha256: 'checksumSha256',
  schemaVersion: 'schemaVersion',
  exportadoEn: 'exportadoEn',
  desde: 'desde',
  periodoId: 'periodoId',
  conteos: 'conteos',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  PerfilAlumno: 'PerfilAlumno',
  ResultadoAlumno: 'ResultadoAlumno',
  MateriaAlumno: 'MateriaAlumno',
  AgendaAlumno: 'AgendaAlumno',
  AvisoAlumno: 'AvisoAlumno',
  HistorialAlumno: 'HistorialAlumno',
  CodigoAcceso: 'CodigoAcceso',
  EventoUsoAlumno: 'EventoUsoAlumno',
  SesionAlumno: 'SesionAlumno',
  SolicitudRevision: 'SolicitudRevision',
  PaqueteSyncDocente: 'PaqueteSyncDocente'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
