
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/PerfilAlumno.js'
export type * from './models/ResultadoAlumno.js'
export type * from './models/MateriaAlumno.js'
export type * from './models/AgendaAlumno.js'
export type * from './models/AvisoAlumno.js'
export type * from './models/HistorialAlumno.js'
export type * from './models/CodigoAcceso.js'
export type * from './models/EventoUsoAlumno.js'
export type * from './models/SesionAlumno.js'
export type * from './models/SolicitudRevision.js'
export type * from './models/PaqueteSyncDocente.js'
export type * from './commonInputTypes.js'