import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const cardsCss = fs.readFileSync(path.join(repoRoot, 'apps/frontend/src/styles/cards.css'), 'utf8');
const entrySource = fs.readFileSync(path.join(repoRoot, 'apps/frontend/src/main.tsx'), 'utf8');
const periodsSource = fs.readFileSync(path.join(repoRoot, 'apps/frontend/src/apps/app_docente/SeccionPeriodos.tsx'), 'utf8');
const guideSource = fs.readFileSync(path.join(repoRoot, 'apps/frontend/src/apps/app_docente/GuiaMateriaVisual.tsx'), 'utf8');
const alumnosSource = fs.readFileSync(path.join(repoRoot, 'apps/frontend/src/apps/app_docente/SeccionAlumnos.tsx'), 'utf8');
const iconSource = fs.readFileSync(path.join(repoRoot, 'apps/frontend/src/ui/iconos.tsx'), 'utf8');

test('el sistema visual de tarjetas es reutilizable y accesible', () => {
  assert.match(entrySource, /styles\/cards\.css/);
  assert.match(cardsCss, /:is\([\s\S]*\.ui-card[\s\S]*\.materias-lista__item[\s\S]*\)\s*\{/);
  assert.match(cardsCss, /\.ui-card--interactive/);
  assert.match(cardsCss, /\.ui-card--featured/);
  assert.match(cardsCss, /\.ui-card--form/);
  assert.match(cardsCss, /\.ui-card--empty/);
  assert.match(cardsCss, /:focus-visible/);
  assert.match(cardsCss, /prefers-reduced-motion/);
  assert.match(cardsCss, /backdrop-filter: blur\(var\(--ui-card-blur\)\)/);
  assert.match(cardsCss, /clip-path: inset\(0 round/);
  assert.match(cardsCss, /--ui-card-surface:.*transparent/);
  assert.match(cardsCss, /radial-gradient\(ellipse at/);
  assert.match(cardsCss, /--ui-card-surface: rgba\(39, 68, 107, 0\.98\)/);
  assert.match(cardsCss, /materias-lista__item/);
  assert.match(cardsCss, /alumnos-lista__item/);
  assert.match(cardsCss, /banco-listado__item/);
  assert.match(cardsCss, /guia-step-card/);
  assert.match(cardsCss, /materia-actions-toggle/);
  assert.match(cardsCss, /alumnos-card__meta/);
  assert.match(cardsCss, /alumno-meta-tag--matricula/);
  assert.match(cardsCss, /alumno-meta-tag--grupo/);
  assert.match(cardsCss, /alumno-meta-tag--correo/);
  assert.match(cardsCss, /RELEASE 1\.8 FINAL[\s\S]*\.alumno-meta-tag--correo[\s\S]*inline-size: max-content/);
  assert.match(cardsCss, /RELEASE 1\.8 FINAL[\s\S]*\.alumno-meta-tag--correo[\s\S]*justify-self: start/);
  assert.match(cardsCss, /materia-card-meta/);
  assert.match(cardsCss, /materia-meta-tag--inicio/);
  assert.match(cardsCss, /materia-meta-tag--fin/);
  assert.match(cardsCss, /materia-meta-tag--grupos/);
  assert.match(cardsCss, /materia-meta-tag--archivada/);
  assert.match(cardsCss, /\.icono\s*\{/);
  assert.match(cardsCss, /shape-rendering: geometricPrecision/);
  assert.match(cardsCss, /\.materia-avatar/);
  assert.match(cardsCss, /:is\([\s\S]*\.materia-avatar[\s\S]*\)\s*\{/);
  assert.match(cardsCss, /\.guia-step-card__icon-orb/);
  assert.match(cardsCss, /\.auth-feature-pill__icon/);
  assert.match(cardsCss, /\.icono :is\(path, circle, line, polyline, polygon, rect\)/);
  assert.match(cardsCss, /\.ui-card-text-title/);
  assert.match(cardsCss, /\.ui-card-text-support/);
  assert.match(cardsCss, /text-shadow:/);
  assert.match(cardsCss, /overflow-wrap: anywhere/);
  assert.match(cardsCss, /--ui-card-surface: rgba\(39, 68, 107, 0\.98\)/);
  assert.match(cardsCss, /antiguo acento superior[\s\S]*display: none/);
  assert.match(cardsCss, /border-top-color: transparent/);
  assert.match(cardsCss, /box-shadow: 0 28px 58px -30px/);
  assert.match(alumnosSource, /alumno-meta-tag--matricula/);
  assert.match(alumnosSource, /alumno-meta-tag--grupo/);
  assert.match(alumnosSource, /alumno-meta-tag--correo/);
  assert.match(periodsSource, /materia-meta-tag--inicio/);
  assert.match(periodsSource, /materia-meta-tag--fin/);
  assert.match(periodsSource, /materia-meta-tag--grupos/);
  assert.match(periodsSource, /ui-card--interactive/);
  assert.match(periodsSource, /accionesAbiertasId/);
  assert.match(periodsSource, /aria-expanded=\{accionesAbiertasId === periodo\._id\}/);
  assert.match(periodsSource, /registroMateriaAbierto/);
  assert.match(periodsSource, /aria-controls="registro-nueva-materia"/);
  assert.match(periodsSource, /Abrir grupo/);
  assert.match(periodsSource, /onAbrirGrupo\?\./);
  assert.match(periodsSource, /<article\s+className="ui-card ui-card--interactive/);
  assert.match(periodsSource, /materia-card-primary-action/);
  assert.doesNotMatch(periodsSource, /role="button"\s+tabIndex=\{0\}/);
  assert.match(guideSource, /localStorage\.getItem\('ep\.guia\.materias\.oculta'\) === 'false'/);
  assert.match(guideSource, /aria-label="Ayuda: Para qué sirve y cómo llenarlo"/);
  assert.match(cardsCss, /materia-card-primary-action/);
  assert.match(cardsCss, /:is\(\.ui-card, \.item-glass\)::before[\s\S]*content: none !important/);
  assert.match(cardsCss, /SISTEMA TRANSVERSAL 1\.5/);
  assert.match(cardsCss, /--ui-canvas: #07162b/);
  assert.match(cardsCss, /body::before/);
  assert.match(cardsCss, /\.materias-panel, \.materias-form, \.materias-seccion-activas/);
  assert.match(cardsCss, /\.alumnos-panel, \.alumnos-form, \.alumnos-explorador/);
  assert.match(cardsCss, /\.asistencias-panel, \.asistencias-filtros-bar/);
  assert.match(cardsCss, /\.temarios-panel, \.temarios-tree-hero-card/);
  assert.match(cardsCss, /\.banco-panel, \.banco-form, \.banco-listado/);
  assert.match(cardsCss, /\.entregas-panel, \.entregas-subpanel/);
  assert.match(cardsCss, /\.calificaciones-layout, \.calificaciones-encuadre-panel/);
  assert.match(cardsCss, /\.sincronizacion-shell/);
  assert.match(cardsCss, /\.cuenta-panel, \.admin-negocio-shell/);
  assert.match(cardsCss, /\.auth-input-box::before[\s\S]*content: none !important/);
  assert.match(cardsCss, /\.auth-input-icon/);
  assert.match(cardsCss, /\.auth-pwd-toggle/);
  assert.match(cardsCss, /\.auth-google-control/);
  assert.match(cardsCss, /:has\(iframe\) \.auth-google-fallback/);
  assert.match(cardsCss, /@media \(max-width: 720px\)/);
  assert.match(cardsCss, /color-mix\(in srgb, var\(--screen-accent/);
  assert.match(iconSource, /\| 'ojo'/);
  assert.match(iconSource, /case 'publicar':[\s\S]*M12 16V3/);
  assert.match(iconSource, /case 'sincronizacion':[\s\S]*M21\.5 2v6/);
  assert.match(iconSource, /data-icono=\{dataIcono\}/);
  assert.match(cardsCss, /\.icono\[data-icono="periodos"\] \{ color: #45d9ee; \}/);
  assert.match(cardsCss, /\.icono\[data-icono="alumnos"\] \{ color: #4fe0ae; \}/);
  assert.match(cardsCss, /\.icono\[data-icono="asistencias"\] \{ color: #ffc45c; \}/);
  assert.match(cardsCss, /\.icono\[data-icono="banco"\] \{ color: #b7a1ff; \}/);
  assert.match(cardsCss, /button\.chip-docente-sesion/);
  assert.match(cardsCss, /\.chip-docente-avatar__status/);
  assert.match(cardsCss, /prefers-reduced-motion/);
  assert.match(cardsCss, /@media \(min-width: 1180px\)[\s\S]*\.shell-docente__header[\s\S]*flex-wrap: nowrap/);
  assert.doesNotMatch(iconSource, /case 'publicar':[\s\S]*case 'sincronizacion':[\s\S]*M21\.5 2v6[\s\S]*M21\.5 2v6/);
  assert.match(fs.readFileSync(path.join(repoRoot, 'apps/frontend/src/apps/app_docente/SeccionAutenticacion.tsx'), 'utf8'), /GoogleLoginConRespaldo/);
  assert.match(fs.readFileSync(path.join(repoRoot, 'apps/frontend/src/apps/app_docente/SeccionAutenticacion.tsx'), 'utf8'), /className="auth-input-icon"/);
});
