
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AgendaAlumno` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model AgendaAlumno
 * 
 */
export type AgendaAlumnoModel = runtime.Types.Result.DefaultSelection<Prisma.$AgendaAlumnoPayload>

export type AggregateAgendaAlumno = {
  _count: AgendaAlumnoCountAggregateOutputType | null
  _min: AgendaAlumnoMinAggregateOutputType | null
  _max: AgendaAlumnoMaxAggregateOutputType | null
}

export type AgendaAlumnoMinAggregateOutputType = {
  id: string | null
  periodoId: string | null
  alumnoId: string | null
  agendaId: string | null
  titulo: string | null
  descripcion: string | null
  fecha: Date | null
  tipo: string | null
  metadata: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AgendaAlumnoMaxAggregateOutputType = {
  id: string | null
  periodoId: string | null
  alumnoId: string | null
  agendaId: string | null
  titulo: string | null
  descripcion: string | null
  fecha: Date | null
  tipo: string | null
  metadata: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AgendaAlumnoCountAggregateOutputType = {
  id: number
  periodoId: number
  alumnoId: number
  agendaId: number
  titulo: number
  descripcion: number
  fecha: number
  tipo: number
  metadata: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AgendaAlumnoMinAggregateInputType = {
  id?: true
  periodoId?: true
  alumnoId?: true
  agendaId?: true
  titulo?: true
  descripcion?: true
  fecha?: true
  tipo?: true
  metadata?: true
  createdAt?: true
  updatedAt?: true
}

export type AgendaAlumnoMaxAggregateInputType = {
  id?: true
  periodoId?: true
  alumnoId?: true
  agendaId?: true
  titulo?: true
  descripcion?: true
  fecha?: true
  tipo?: true
  metadata?: true
  createdAt?: true
  updatedAt?: true
}

export type AgendaAlumnoCountAggregateInputType = {
  id?: true
  periodoId?: true
  alumnoId?: true
  agendaId?: true
  titulo?: true
  descripcion?: true
  fecha?: true
  tipo?: true
  metadata?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AgendaAlumnoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AgendaAlumno to aggregate.
   */
  where?: Prisma.AgendaAlumnoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgendaAlumnos to fetch.
   */
  orderBy?: Prisma.AgendaAlumnoOrderByWithRelationInput | Prisma.AgendaAlumnoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AgendaAlumnoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgendaAlumnos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgendaAlumnos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AgendaAlumnos
  **/
  _count?: true | AgendaAlumnoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AgendaAlumnoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AgendaAlumnoMaxAggregateInputType
}

export type GetAgendaAlumnoAggregateType<T extends AgendaAlumnoAggregateArgs> = {
      [P in keyof T & keyof AggregateAgendaAlumno]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAgendaAlumno[P]>
    : Prisma.GetScalarType<T[P], AggregateAgendaAlumno[P]>
}




export type AgendaAlumnoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AgendaAlumnoWhereInput
  orderBy?: Prisma.AgendaAlumnoOrderByWithAggregationInput | Prisma.AgendaAlumnoOrderByWithAggregationInput[]
  by: Prisma.AgendaAlumnoScalarFieldEnum[] | Prisma.AgendaAlumnoScalarFieldEnum
  having?: Prisma.AgendaAlumnoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AgendaAlumnoCountAggregateInputType | true
  _min?: AgendaAlumnoMinAggregateInputType
  _max?: AgendaAlumnoMaxAggregateInputType
}

export type AgendaAlumnoGroupByOutputType = {
  id: string
  periodoId: string
  alumnoId: string
  agendaId: string
  titulo: string
  descripcion: string | null
  fecha: Date
  tipo: string
  metadata: string | null
  createdAt: Date
  updatedAt: Date
  _count: AgendaAlumnoCountAggregateOutputType | null
  _min: AgendaAlumnoMinAggregateOutputType | null
  _max: AgendaAlumnoMaxAggregateOutputType | null
}

type GetAgendaAlumnoGroupByPayload<T extends AgendaAlumnoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AgendaAlumnoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AgendaAlumnoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AgendaAlumnoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AgendaAlumnoGroupByOutputType[P]>
      }
    >
  >



export type AgendaAlumnoWhereInput = {
  AND?: Prisma.AgendaAlumnoWhereInput | Prisma.AgendaAlumnoWhereInput[]
  OR?: Prisma.AgendaAlumnoWhereInput[]
  NOT?: Prisma.AgendaAlumnoWhereInput | Prisma.AgendaAlumnoWhereInput[]
  id?: Prisma.StringFilter<"AgendaAlumno"> | string
  periodoId?: Prisma.StringFilter<"AgendaAlumno"> | string
  alumnoId?: Prisma.StringFilter<"AgendaAlumno"> | string
  agendaId?: Prisma.StringFilter<"AgendaAlumno"> | string
  titulo?: Prisma.StringFilter<"AgendaAlumno"> | string
  descripcion?: Prisma.StringNullableFilter<"AgendaAlumno"> | string | null
  fecha?: Prisma.DateTimeFilter<"AgendaAlumno"> | Date | string
  tipo?: Prisma.StringFilter<"AgendaAlumno"> | string
  metadata?: Prisma.StringNullableFilter<"AgendaAlumno"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AgendaAlumno"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AgendaAlumno"> | Date | string
}

export type AgendaAlumnoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  periodoId?: Prisma.SortOrder
  alumnoId?: Prisma.SortOrder
  agendaId?: Prisma.SortOrder
  titulo?: Prisma.SortOrder
  descripcion?: Prisma.SortOrderInput | Prisma.SortOrder
  fecha?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AgendaAlumnoWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  periodoId_alumnoId_agendaId?: Prisma.AgendaAlumnoPeriodoIdAlumnoIdAgendaIdCompoundUniqueInput
  AND?: Prisma.AgendaAlumnoWhereInput | Prisma.AgendaAlumnoWhereInput[]
  OR?: Prisma.AgendaAlumnoWhereInput[]
  NOT?: Prisma.AgendaAlumnoWhereInput | Prisma.AgendaAlumnoWhereInput[]
  periodoId?: Prisma.StringFilter<"AgendaAlumno"> | string
  alumnoId?: Prisma.StringFilter<"AgendaAlumno"> | string
  agendaId?: Prisma.StringFilter<"AgendaAlumno"> | string
  titulo?: Prisma.StringFilter<"AgendaAlumno"> | string
  descripcion?: Prisma.StringNullableFilter<"AgendaAlumno"> | string | null
  fecha?: Prisma.DateTimeFilter<"AgendaAlumno"> | Date | string
  tipo?: Prisma.StringFilter<"AgendaAlumno"> | string
  metadata?: Prisma.StringNullableFilter<"AgendaAlumno"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AgendaAlumno"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AgendaAlumno"> | Date | string
}, "id" | "periodoId_alumnoId_agendaId">

export type AgendaAlumnoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  periodoId?: Prisma.SortOrder
  alumnoId?: Prisma.SortOrder
  agendaId?: Prisma.SortOrder
  titulo?: Prisma.SortOrder
  descripcion?: Prisma.SortOrderInput | Prisma.SortOrder
  fecha?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AgendaAlumnoCountOrderByAggregateInput
  _max?: Prisma.AgendaAlumnoMaxOrderByAggregateInput
  _min?: Prisma.AgendaAlumnoMinOrderByAggregateInput
}

export type AgendaAlumnoScalarWhereWithAggregatesInput = {
  AND?: Prisma.AgendaAlumnoScalarWhereWithAggregatesInput | Prisma.AgendaAlumnoScalarWhereWithAggregatesInput[]
  OR?: Prisma.AgendaAlumnoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AgendaAlumnoScalarWhereWithAggregatesInput | Prisma.AgendaAlumnoScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AgendaAlumno"> | string
  periodoId?: Prisma.StringWithAggregatesFilter<"AgendaAlumno"> | string
  alumnoId?: Prisma.StringWithAggregatesFilter<"AgendaAlumno"> | string
  agendaId?: Prisma.StringWithAggregatesFilter<"AgendaAlumno"> | string
  titulo?: Prisma.StringWithAggregatesFilter<"AgendaAlumno"> | string
  descripcion?: Prisma.StringNullableWithAggregatesFilter<"AgendaAlumno"> | string | null
  fecha?: Prisma.DateTimeWithAggregatesFilter<"AgendaAlumno"> | Date | string
  tipo?: Prisma.StringWithAggregatesFilter<"AgendaAlumno"> | string
  metadata?: Prisma.StringNullableWithAggregatesFilter<"AgendaAlumno"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AgendaAlumno"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AgendaAlumno"> | Date | string
}

export type AgendaAlumnoCreateInput = {
  id?: string
  periodoId: string
  alumnoId: string
  agendaId: string
  titulo: string
  descripcion?: string | null
  fecha: Date | string
  tipo?: string
  metadata?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AgendaAlumnoUncheckedCreateInput = {
  id?: string
  periodoId: string
  alumnoId: string
  agendaId: string
  titulo: string
  descripcion?: string | null
  fecha: Date | string
  tipo?: string
  metadata?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AgendaAlumnoUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  periodoId?: Prisma.StringFieldUpdateOperationsInput | string
  alumnoId?: Prisma.StringFieldUpdateOperationsInput | string
  agendaId?: Prisma.StringFieldUpdateOperationsInput | string
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tipo?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgendaAlumnoUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  periodoId?: Prisma.StringFieldUpdateOperationsInput | string
  alumnoId?: Prisma.StringFieldUpdateOperationsInput | string
  agendaId?: Prisma.StringFieldUpdateOperationsInput | string
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tipo?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgendaAlumnoCreateManyInput = {
  id?: string
  periodoId: string
  alumnoId: string
  agendaId: string
  titulo: string
  descripcion?: string | null
  fecha: Date | string
  tipo?: string
  metadata?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AgendaAlumnoUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  periodoId?: Prisma.StringFieldUpdateOperationsInput | string
  alumnoId?: Prisma.StringFieldUpdateOperationsInput | string
  agendaId?: Prisma.StringFieldUpdateOperationsInput | string
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tipo?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgendaAlumnoUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  periodoId?: Prisma.StringFieldUpdateOperationsInput | string
  alumnoId?: Prisma.StringFieldUpdateOperationsInput | string
  agendaId?: Prisma.StringFieldUpdateOperationsInput | string
  titulo?: Prisma.StringFieldUpdateOperationsInput | string
  descripcion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tipo?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgendaAlumnoPeriodoIdAlumnoIdAgendaIdCompoundUniqueInput = {
  periodoId: string
  alumnoId: string
  agendaId: string
}

export type AgendaAlumnoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  periodoId?: Prisma.SortOrder
  alumnoId?: Prisma.SortOrder
  agendaId?: Prisma.SortOrder
  titulo?: Prisma.SortOrder
  descripcion?: Prisma.SortOrder
  fecha?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AgendaAlumnoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  periodoId?: Prisma.SortOrder
  alumnoId?: Prisma.SortOrder
  agendaId?: Prisma.SortOrder
  titulo?: Prisma.SortOrder
  descripcion?: Prisma.SortOrder
  fecha?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AgendaAlumnoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  periodoId?: Prisma.SortOrder
  alumnoId?: Prisma.SortOrder
  agendaId?: Prisma.SortOrder
  titulo?: Prisma.SortOrder
  descripcion?: Prisma.SortOrder
  fecha?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}



export type AgendaAlumnoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  periodoId?: boolean
  alumnoId?: boolean
  agendaId?: boolean
  titulo?: boolean
  descripcion?: boolean
  fecha?: boolean
  tipo?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["agendaAlumno"]>

export type AgendaAlumnoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  periodoId?: boolean
  alumnoId?: boolean
  agendaId?: boolean
  titulo?: boolean
  descripcion?: boolean
  fecha?: boolean
  tipo?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["agendaAlumno"]>

export type AgendaAlumnoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  periodoId?: boolean
  alumnoId?: boolean
  agendaId?: boolean
  titulo?: boolean
  descripcion?: boolean
  fecha?: boolean
  tipo?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["agendaAlumno"]>

export type AgendaAlumnoSelectScalar = {
  id?: boolean
  periodoId?: boolean
  alumnoId?: boolean
  agendaId?: boolean
  titulo?: boolean
  descripcion?: boolean
  fecha?: boolean
  tipo?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AgendaAlumnoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "periodoId" | "alumnoId" | "agendaId" | "titulo" | "descripcion" | "fecha" | "tipo" | "metadata" | "createdAt" | "updatedAt", ExtArgs["result"]["agendaAlumno"]>

export type $AgendaAlumnoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AgendaAlumno"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    periodoId: string
    alumnoId: string
    agendaId: string
    titulo: string
    descripcion: string | null
    fecha: Date
    tipo: string
    metadata: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["agendaAlumno"]>
  composites: {}
}

export type AgendaAlumnoGetPayload<S extends boolean | null | undefined | AgendaAlumnoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AgendaAlumnoPayload, S>

export type AgendaAlumnoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AgendaAlumnoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AgendaAlumnoCountAggregateInputType | true
  }

export interface AgendaAlumnoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AgendaAlumno'], meta: { name: 'AgendaAlumno' } }
  /**
   * Find zero or one AgendaAlumno that matches the filter.
   * @param {AgendaAlumnoFindUniqueArgs} args - Arguments to find a AgendaAlumno
   * @example
   * // Get one AgendaAlumno
   * const agendaAlumno = await prisma.agendaAlumno.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AgendaAlumnoFindUniqueArgs>(args: Prisma.SelectSubset<T, AgendaAlumnoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AgendaAlumnoClient<runtime.Types.Result.GetResult<Prisma.$AgendaAlumnoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AgendaAlumno that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AgendaAlumnoFindUniqueOrThrowArgs} args - Arguments to find a AgendaAlumno
   * @example
   * // Get one AgendaAlumno
   * const agendaAlumno = await prisma.agendaAlumno.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AgendaAlumnoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AgendaAlumnoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgendaAlumnoClient<runtime.Types.Result.GetResult<Prisma.$AgendaAlumnoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AgendaAlumno that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgendaAlumnoFindFirstArgs} args - Arguments to find a AgendaAlumno
   * @example
   * // Get one AgendaAlumno
   * const agendaAlumno = await prisma.agendaAlumno.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AgendaAlumnoFindFirstArgs>(args?: Prisma.SelectSubset<T, AgendaAlumnoFindFirstArgs<ExtArgs>>): Prisma.Prisma__AgendaAlumnoClient<runtime.Types.Result.GetResult<Prisma.$AgendaAlumnoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AgendaAlumno that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgendaAlumnoFindFirstOrThrowArgs} args - Arguments to find a AgendaAlumno
   * @example
   * // Get one AgendaAlumno
   * const agendaAlumno = await prisma.agendaAlumno.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AgendaAlumnoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AgendaAlumnoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgendaAlumnoClient<runtime.Types.Result.GetResult<Prisma.$AgendaAlumnoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AgendaAlumnos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgendaAlumnoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AgendaAlumnos
   * const agendaAlumnos = await prisma.agendaAlumno.findMany()
   * 
   * // Get first 10 AgendaAlumnos
   * const agendaAlumnos = await prisma.agendaAlumno.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const agendaAlumnoWithIdOnly = await prisma.agendaAlumno.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AgendaAlumnoFindManyArgs>(args?: Prisma.SelectSubset<T, AgendaAlumnoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgendaAlumnoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AgendaAlumno.
   * @param {AgendaAlumnoCreateArgs} args - Arguments to create a AgendaAlumno.
   * @example
   * // Create one AgendaAlumno
   * const AgendaAlumno = await prisma.agendaAlumno.create({
   *   data: {
   *     // ... data to create a AgendaAlumno
   *   }
   * })
   * 
   */
  create<T extends AgendaAlumnoCreateArgs>(args: Prisma.SelectSubset<T, AgendaAlumnoCreateArgs<ExtArgs>>): Prisma.Prisma__AgendaAlumnoClient<runtime.Types.Result.GetResult<Prisma.$AgendaAlumnoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AgendaAlumnos.
   * @param {AgendaAlumnoCreateManyArgs} args - Arguments to create many AgendaAlumnos.
   * @example
   * // Create many AgendaAlumnos
   * const agendaAlumno = await prisma.agendaAlumno.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AgendaAlumnoCreateManyArgs>(args?: Prisma.SelectSubset<T, AgendaAlumnoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AgendaAlumnos and returns the data saved in the database.
   * @param {AgendaAlumnoCreateManyAndReturnArgs} args - Arguments to create many AgendaAlumnos.
   * @example
   * // Create many AgendaAlumnos
   * const agendaAlumno = await prisma.agendaAlumno.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AgendaAlumnos and only return the `id`
   * const agendaAlumnoWithIdOnly = await prisma.agendaAlumno.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AgendaAlumnoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AgendaAlumnoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgendaAlumnoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AgendaAlumno.
   * @param {AgendaAlumnoDeleteArgs} args - Arguments to delete one AgendaAlumno.
   * @example
   * // Delete one AgendaAlumno
   * const AgendaAlumno = await prisma.agendaAlumno.delete({
   *   where: {
   *     // ... filter to delete one AgendaAlumno
   *   }
   * })
   * 
   */
  delete<T extends AgendaAlumnoDeleteArgs>(args: Prisma.SelectSubset<T, AgendaAlumnoDeleteArgs<ExtArgs>>): Prisma.Prisma__AgendaAlumnoClient<runtime.Types.Result.GetResult<Prisma.$AgendaAlumnoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AgendaAlumno.
   * @param {AgendaAlumnoUpdateArgs} args - Arguments to update one AgendaAlumno.
   * @example
   * // Update one AgendaAlumno
   * const agendaAlumno = await prisma.agendaAlumno.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AgendaAlumnoUpdateArgs>(args: Prisma.SelectSubset<T, AgendaAlumnoUpdateArgs<ExtArgs>>): Prisma.Prisma__AgendaAlumnoClient<runtime.Types.Result.GetResult<Prisma.$AgendaAlumnoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AgendaAlumnos.
   * @param {AgendaAlumnoDeleteManyArgs} args - Arguments to filter AgendaAlumnos to delete.
   * @example
   * // Delete a few AgendaAlumnos
   * const { count } = await prisma.agendaAlumno.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AgendaAlumnoDeleteManyArgs>(args?: Prisma.SelectSubset<T, AgendaAlumnoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AgendaAlumnos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgendaAlumnoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AgendaAlumnos
   * const agendaAlumno = await prisma.agendaAlumno.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AgendaAlumnoUpdateManyArgs>(args: Prisma.SelectSubset<T, AgendaAlumnoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AgendaAlumnos and returns the data updated in the database.
   * @param {AgendaAlumnoUpdateManyAndReturnArgs} args - Arguments to update many AgendaAlumnos.
   * @example
   * // Update many AgendaAlumnos
   * const agendaAlumno = await prisma.agendaAlumno.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AgendaAlumnos and only return the `id`
   * const agendaAlumnoWithIdOnly = await prisma.agendaAlumno.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AgendaAlumnoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AgendaAlumnoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgendaAlumnoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AgendaAlumno.
   * @param {AgendaAlumnoUpsertArgs} args - Arguments to update or create a AgendaAlumno.
   * @example
   * // Update or create a AgendaAlumno
   * const agendaAlumno = await prisma.agendaAlumno.upsert({
   *   create: {
   *     // ... data to create a AgendaAlumno
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AgendaAlumno we want to update
   *   }
   * })
   */
  upsert<T extends AgendaAlumnoUpsertArgs>(args: Prisma.SelectSubset<T, AgendaAlumnoUpsertArgs<ExtArgs>>): Prisma.Prisma__AgendaAlumnoClient<runtime.Types.Result.GetResult<Prisma.$AgendaAlumnoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AgendaAlumnos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgendaAlumnoCountArgs} args - Arguments to filter AgendaAlumnos to count.
   * @example
   * // Count the number of AgendaAlumnos
   * const count = await prisma.agendaAlumno.count({
   *   where: {
   *     // ... the filter for the AgendaAlumnos we want to count
   *   }
   * })
  **/
  count<T extends AgendaAlumnoCountArgs>(
    args?: Prisma.Subset<T, AgendaAlumnoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AgendaAlumnoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AgendaAlumno.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgendaAlumnoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AgendaAlumnoAggregateArgs>(args: Prisma.Subset<T, AgendaAlumnoAggregateArgs>): Prisma.PrismaPromise<GetAgendaAlumnoAggregateType<T>>

  /**
   * Group by AgendaAlumno.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgendaAlumnoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AgendaAlumnoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AgendaAlumnoGroupByArgs['orderBy'] }
      : { orderBy?: AgendaAlumnoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AgendaAlumnoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAgendaAlumnoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AgendaAlumno model
 */
readonly fields: AgendaAlumnoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AgendaAlumno.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AgendaAlumnoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AgendaAlumno model
 */
export interface AgendaAlumnoFieldRefs {
  readonly id: Prisma.FieldRef<"AgendaAlumno", 'String'>
  readonly periodoId: Prisma.FieldRef<"AgendaAlumno", 'String'>
  readonly alumnoId: Prisma.FieldRef<"AgendaAlumno", 'String'>
  readonly agendaId: Prisma.FieldRef<"AgendaAlumno", 'String'>
  readonly titulo: Prisma.FieldRef<"AgendaAlumno", 'String'>
  readonly descripcion: Prisma.FieldRef<"AgendaAlumno", 'String'>
  readonly fecha: Prisma.FieldRef<"AgendaAlumno", 'DateTime'>
  readonly tipo: Prisma.FieldRef<"AgendaAlumno", 'String'>
  readonly metadata: Prisma.FieldRef<"AgendaAlumno", 'String'>
  readonly createdAt: Prisma.FieldRef<"AgendaAlumno", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AgendaAlumno", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AgendaAlumno findUnique
 */
export type AgendaAlumnoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgendaAlumno
   */
  select?: Prisma.AgendaAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgendaAlumno
   */
  omit?: Prisma.AgendaAlumnoOmit<ExtArgs> | null
  /**
   * Filter, which AgendaAlumno to fetch.
   */
  where: Prisma.AgendaAlumnoWhereUniqueInput
}

/**
 * AgendaAlumno findUniqueOrThrow
 */
export type AgendaAlumnoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgendaAlumno
   */
  select?: Prisma.AgendaAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgendaAlumno
   */
  omit?: Prisma.AgendaAlumnoOmit<ExtArgs> | null
  /**
   * Filter, which AgendaAlumno to fetch.
   */
  where: Prisma.AgendaAlumnoWhereUniqueInput
}

/**
 * AgendaAlumno findFirst
 */
export type AgendaAlumnoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgendaAlumno
   */
  select?: Prisma.AgendaAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgendaAlumno
   */
  omit?: Prisma.AgendaAlumnoOmit<ExtArgs> | null
  /**
   * Filter, which AgendaAlumno to fetch.
   */
  where?: Prisma.AgendaAlumnoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgendaAlumnos to fetch.
   */
  orderBy?: Prisma.AgendaAlumnoOrderByWithRelationInput | Prisma.AgendaAlumnoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AgendaAlumnos.
   */
  cursor?: Prisma.AgendaAlumnoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgendaAlumnos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgendaAlumnos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AgendaAlumnos.
   */
  distinct?: Prisma.AgendaAlumnoScalarFieldEnum | Prisma.AgendaAlumnoScalarFieldEnum[]
}

/**
 * AgendaAlumno findFirstOrThrow
 */
export type AgendaAlumnoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgendaAlumno
   */
  select?: Prisma.AgendaAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgendaAlumno
   */
  omit?: Prisma.AgendaAlumnoOmit<ExtArgs> | null
  /**
   * Filter, which AgendaAlumno to fetch.
   */
  where?: Prisma.AgendaAlumnoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgendaAlumnos to fetch.
   */
  orderBy?: Prisma.AgendaAlumnoOrderByWithRelationInput | Prisma.AgendaAlumnoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AgendaAlumnos.
   */
  cursor?: Prisma.AgendaAlumnoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgendaAlumnos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgendaAlumnos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AgendaAlumnos.
   */
  distinct?: Prisma.AgendaAlumnoScalarFieldEnum | Prisma.AgendaAlumnoScalarFieldEnum[]
}

/**
 * AgendaAlumno findMany
 */
export type AgendaAlumnoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgendaAlumno
   */
  select?: Prisma.AgendaAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgendaAlumno
   */
  omit?: Prisma.AgendaAlumnoOmit<ExtArgs> | null
  /**
   * Filter, which AgendaAlumnos to fetch.
   */
  where?: Prisma.AgendaAlumnoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgendaAlumnos to fetch.
   */
  orderBy?: Prisma.AgendaAlumnoOrderByWithRelationInput | Prisma.AgendaAlumnoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AgendaAlumnos.
   */
  cursor?: Prisma.AgendaAlumnoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgendaAlumnos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgendaAlumnos.
   */
  skip?: number
  distinct?: Prisma.AgendaAlumnoScalarFieldEnum | Prisma.AgendaAlumnoScalarFieldEnum[]
}

/**
 * AgendaAlumno create
 */
export type AgendaAlumnoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgendaAlumno
   */
  select?: Prisma.AgendaAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgendaAlumno
   */
  omit?: Prisma.AgendaAlumnoOmit<ExtArgs> | null
  /**
   * The data needed to create a AgendaAlumno.
   */
  data: Prisma.XOR<Prisma.AgendaAlumnoCreateInput, Prisma.AgendaAlumnoUncheckedCreateInput>
}

/**
 * AgendaAlumno createMany
 */
export type AgendaAlumnoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AgendaAlumnos.
   */
  data: Prisma.AgendaAlumnoCreateManyInput | Prisma.AgendaAlumnoCreateManyInput[]
}

/**
 * AgendaAlumno createManyAndReturn
 */
export type AgendaAlumnoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgendaAlumno
   */
  select?: Prisma.AgendaAlumnoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AgendaAlumno
   */
  omit?: Prisma.AgendaAlumnoOmit<ExtArgs> | null
  /**
   * The data used to create many AgendaAlumnos.
   */
  data: Prisma.AgendaAlumnoCreateManyInput | Prisma.AgendaAlumnoCreateManyInput[]
}

/**
 * AgendaAlumno update
 */
export type AgendaAlumnoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgendaAlumno
   */
  select?: Prisma.AgendaAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgendaAlumno
   */
  omit?: Prisma.AgendaAlumnoOmit<ExtArgs> | null
  /**
   * The data needed to update a AgendaAlumno.
   */
  data: Prisma.XOR<Prisma.AgendaAlumnoUpdateInput, Prisma.AgendaAlumnoUncheckedUpdateInput>
  /**
   * Choose, which AgendaAlumno to update.
   */
  where: Prisma.AgendaAlumnoWhereUniqueInput
}

/**
 * AgendaAlumno updateMany
 */
export type AgendaAlumnoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AgendaAlumnos.
   */
  data: Prisma.XOR<Prisma.AgendaAlumnoUpdateManyMutationInput, Prisma.AgendaAlumnoUncheckedUpdateManyInput>
  /**
   * Filter which AgendaAlumnos to update
   */
  where?: Prisma.AgendaAlumnoWhereInput
  /**
   * Limit how many AgendaAlumnos to update.
   */
  limit?: number
}

/**
 * AgendaAlumno updateManyAndReturn
 */
export type AgendaAlumnoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgendaAlumno
   */
  select?: Prisma.AgendaAlumnoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AgendaAlumno
   */
  omit?: Prisma.AgendaAlumnoOmit<ExtArgs> | null
  /**
   * The data used to update AgendaAlumnos.
   */
  data: Prisma.XOR<Prisma.AgendaAlumnoUpdateManyMutationInput, Prisma.AgendaAlumnoUncheckedUpdateManyInput>
  /**
   * Filter which AgendaAlumnos to update
   */
  where?: Prisma.AgendaAlumnoWhereInput
  /**
   * Limit how many AgendaAlumnos to update.
   */
  limit?: number
}

/**
 * AgendaAlumno upsert
 */
export type AgendaAlumnoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgendaAlumno
   */
  select?: Prisma.AgendaAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgendaAlumno
   */
  omit?: Prisma.AgendaAlumnoOmit<ExtArgs> | null
  /**
   * The filter to search for the AgendaAlumno to update in case it exists.
   */
  where: Prisma.AgendaAlumnoWhereUniqueInput
  /**
   * In case the AgendaAlumno found by the `where` argument doesn't exist, create a new AgendaAlumno with this data.
   */
  create: Prisma.XOR<Prisma.AgendaAlumnoCreateInput, Prisma.AgendaAlumnoUncheckedCreateInput>
  /**
   * In case the AgendaAlumno was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AgendaAlumnoUpdateInput, Prisma.AgendaAlumnoUncheckedUpdateInput>
}

/**
 * AgendaAlumno delete
 */
export type AgendaAlumnoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgendaAlumno
   */
  select?: Prisma.AgendaAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgendaAlumno
   */
  omit?: Prisma.AgendaAlumnoOmit<ExtArgs> | null
  /**
   * Filter which AgendaAlumno to delete.
   */
  where: Prisma.AgendaAlumnoWhereUniqueInput
}

/**
 * AgendaAlumno deleteMany
 */
export type AgendaAlumnoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AgendaAlumnos to delete
   */
  where?: Prisma.AgendaAlumnoWhereInput
  /**
   * Limit how many AgendaAlumnos to delete.
   */
  limit?: number
}

/**
 * AgendaAlumno without action
 */
export type AgendaAlumnoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgendaAlumno
   */
  select?: Prisma.AgendaAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgendaAlumno
   */
  omit?: Prisma.AgendaAlumnoOmit<ExtArgs> | null
}
