
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `HistorialAlumno` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model HistorialAlumno
 * 
 */
export type HistorialAlumnoModel = runtime.Types.Result.DefaultSelection<Prisma.$HistorialAlumnoPayload>

export type AggregateHistorialAlumno = {
  _count: HistorialAlumnoCountAggregateOutputType | null
  _avg: HistorialAlumnoAvgAggregateOutputType | null
  _sum: HistorialAlumnoSumAggregateOutputType | null
  _min: HistorialAlumnoMinAggregateOutputType | null
  _max: HistorialAlumnoMaxAggregateOutputType | null
}

export type HistorialAlumnoAvgAggregateOutputType = {
  aciertos: number | null
  totalReactivos: number | null
}

export type HistorialAlumnoSumAggregateOutputType = {
  aciertos: number | null
  totalReactivos: number | null
}

export type HistorialAlumnoMinAggregateOutputType = {
  id: string | null
  periodoId: string | null
  alumnoId: string | null
  historialId: string | null
  folio: string | null
  tipoExamen: string | null
  calificacionTexto: string | null
  aciertos: number | null
  totalReactivos: number | null
  fecha: Date | null
  metadata: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type HistorialAlumnoMaxAggregateOutputType = {
  id: string | null
  periodoId: string | null
  alumnoId: string | null
  historialId: string | null
  folio: string | null
  tipoExamen: string | null
  calificacionTexto: string | null
  aciertos: number | null
  totalReactivos: number | null
  fecha: Date | null
  metadata: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type HistorialAlumnoCountAggregateOutputType = {
  id: number
  periodoId: number
  alumnoId: number
  historialId: number
  folio: number
  tipoExamen: number
  calificacionTexto: number
  aciertos: number
  totalReactivos: number
  fecha: number
  metadata: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type HistorialAlumnoAvgAggregateInputType = {
  aciertos?: true
  totalReactivos?: true
}

export type HistorialAlumnoSumAggregateInputType = {
  aciertos?: true
  totalReactivos?: true
}

export type HistorialAlumnoMinAggregateInputType = {
  id?: true
  periodoId?: true
  alumnoId?: true
  historialId?: true
  folio?: true
  tipoExamen?: true
  calificacionTexto?: true
  aciertos?: true
  totalReactivos?: true
  fecha?: true
  metadata?: true
  createdAt?: true
  updatedAt?: true
}

export type HistorialAlumnoMaxAggregateInputType = {
  id?: true
  periodoId?: true
  alumnoId?: true
  historialId?: true
  folio?: true
  tipoExamen?: true
  calificacionTexto?: true
  aciertos?: true
  totalReactivos?: true
  fecha?: true
  metadata?: true
  createdAt?: true
  updatedAt?: true
}

export type HistorialAlumnoCountAggregateInputType = {
  id?: true
  periodoId?: true
  alumnoId?: true
  historialId?: true
  folio?: true
  tipoExamen?: true
  calificacionTexto?: true
  aciertos?: true
  totalReactivos?: true
  fecha?: true
  metadata?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type HistorialAlumnoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which HistorialAlumno to aggregate.
   */
  where?: Prisma.HistorialAlumnoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HistorialAlumnos to fetch.
   */
  orderBy?: Prisma.HistorialAlumnoOrderByWithRelationInput | Prisma.HistorialAlumnoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.HistorialAlumnoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HistorialAlumnos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HistorialAlumnos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned HistorialAlumnos
  **/
  _count?: true | HistorialAlumnoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: HistorialAlumnoAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: HistorialAlumnoSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HistorialAlumnoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HistorialAlumnoMaxAggregateInputType
}

export type GetHistorialAlumnoAggregateType<T extends HistorialAlumnoAggregateArgs> = {
      [P in keyof T & keyof AggregateHistorialAlumno]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHistorialAlumno[P]>
    : Prisma.GetScalarType<T[P], AggregateHistorialAlumno[P]>
}




export type HistorialAlumnoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HistorialAlumnoWhereInput
  orderBy?: Prisma.HistorialAlumnoOrderByWithAggregationInput | Prisma.HistorialAlumnoOrderByWithAggregationInput[]
  by: Prisma.HistorialAlumnoScalarFieldEnum[] | Prisma.HistorialAlumnoScalarFieldEnum
  having?: Prisma.HistorialAlumnoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HistorialAlumnoCountAggregateInputType | true
  _avg?: HistorialAlumnoAvgAggregateInputType
  _sum?: HistorialAlumnoSumAggregateInputType
  _min?: HistorialAlumnoMinAggregateInputType
  _max?: HistorialAlumnoMaxAggregateInputType
}

export type HistorialAlumnoGroupByOutputType = {
  id: string
  periodoId: string
  alumnoId: string
  historialId: string
  folio: string | null
  tipoExamen: string | null
  calificacionTexto: string | null
  aciertos: number | null
  totalReactivos: number | null
  fecha: Date
  metadata: string | null
  createdAt: Date
  updatedAt: Date
  _count: HistorialAlumnoCountAggregateOutputType | null
  _avg: HistorialAlumnoAvgAggregateOutputType | null
  _sum: HistorialAlumnoSumAggregateOutputType | null
  _min: HistorialAlumnoMinAggregateOutputType | null
  _max: HistorialAlumnoMaxAggregateOutputType | null
}

type GetHistorialAlumnoGroupByPayload<T extends HistorialAlumnoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HistorialAlumnoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HistorialAlumnoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HistorialAlumnoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HistorialAlumnoGroupByOutputType[P]>
      }
    >
  >



export type HistorialAlumnoWhereInput = {
  AND?: Prisma.HistorialAlumnoWhereInput | Prisma.HistorialAlumnoWhereInput[]
  OR?: Prisma.HistorialAlumnoWhereInput[]
  NOT?: Prisma.HistorialAlumnoWhereInput | Prisma.HistorialAlumnoWhereInput[]
  id?: Prisma.StringFilter<"HistorialAlumno"> | string
  periodoId?: Prisma.StringFilter<"HistorialAlumno"> | string
  alumnoId?: Prisma.StringFilter<"HistorialAlumno"> | string
  historialId?: Prisma.StringFilter<"HistorialAlumno"> | string
  folio?: Prisma.StringNullableFilter<"HistorialAlumno"> | string | null
  tipoExamen?: Prisma.StringNullableFilter<"HistorialAlumno"> | string | null
  calificacionTexto?: Prisma.StringNullableFilter<"HistorialAlumno"> | string | null
  aciertos?: Prisma.IntNullableFilter<"HistorialAlumno"> | number | null
  totalReactivos?: Prisma.IntNullableFilter<"HistorialAlumno"> | number | null
  fecha?: Prisma.DateTimeFilter<"HistorialAlumno"> | Date | string
  metadata?: Prisma.StringNullableFilter<"HistorialAlumno"> | string | null
  createdAt?: Prisma.DateTimeFilter<"HistorialAlumno"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"HistorialAlumno"> | Date | string
}

export type HistorialAlumnoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  periodoId?: Prisma.SortOrder
  alumnoId?: Prisma.SortOrder
  historialId?: Prisma.SortOrder
  folio?: Prisma.SortOrderInput | Prisma.SortOrder
  tipoExamen?: Prisma.SortOrderInput | Prisma.SortOrder
  calificacionTexto?: Prisma.SortOrderInput | Prisma.SortOrder
  aciertos?: Prisma.SortOrderInput | Prisma.SortOrder
  totalReactivos?: Prisma.SortOrderInput | Prisma.SortOrder
  fecha?: Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type HistorialAlumnoWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  periodoId_alumnoId_historialId?: Prisma.HistorialAlumnoPeriodoIdAlumnoIdHistorialIdCompoundUniqueInput
  AND?: Prisma.HistorialAlumnoWhereInput | Prisma.HistorialAlumnoWhereInput[]
  OR?: Prisma.HistorialAlumnoWhereInput[]
  NOT?: Prisma.HistorialAlumnoWhereInput | Prisma.HistorialAlumnoWhereInput[]
  periodoId?: Prisma.StringFilter<"HistorialAlumno"> | string
  alumnoId?: Prisma.StringFilter<"HistorialAlumno"> | string
  historialId?: Prisma.StringFilter<"HistorialAlumno"> | string
  folio?: Prisma.StringNullableFilter<"HistorialAlumno"> | string | null
  tipoExamen?: Prisma.StringNullableFilter<"HistorialAlumno"> | string | null
  calificacionTexto?: Prisma.StringNullableFilter<"HistorialAlumno"> | string | null
  aciertos?: Prisma.IntNullableFilter<"HistorialAlumno"> | number | null
  totalReactivos?: Prisma.IntNullableFilter<"HistorialAlumno"> | number | null
  fecha?: Prisma.DateTimeFilter<"HistorialAlumno"> | Date | string
  metadata?: Prisma.StringNullableFilter<"HistorialAlumno"> | string | null
  createdAt?: Prisma.DateTimeFilter<"HistorialAlumno"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"HistorialAlumno"> | Date | string
}, "id" | "periodoId_alumnoId_historialId">

export type HistorialAlumnoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  periodoId?: Prisma.SortOrder
  alumnoId?: Prisma.SortOrder
  historialId?: Prisma.SortOrder
  folio?: Prisma.SortOrderInput | Prisma.SortOrder
  tipoExamen?: Prisma.SortOrderInput | Prisma.SortOrder
  calificacionTexto?: Prisma.SortOrderInput | Prisma.SortOrder
  aciertos?: Prisma.SortOrderInput | Prisma.SortOrder
  totalReactivos?: Prisma.SortOrderInput | Prisma.SortOrder
  fecha?: Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.HistorialAlumnoCountOrderByAggregateInput
  _avg?: Prisma.HistorialAlumnoAvgOrderByAggregateInput
  _max?: Prisma.HistorialAlumnoMaxOrderByAggregateInput
  _min?: Prisma.HistorialAlumnoMinOrderByAggregateInput
  _sum?: Prisma.HistorialAlumnoSumOrderByAggregateInput
}

export type HistorialAlumnoScalarWhereWithAggregatesInput = {
  AND?: Prisma.HistorialAlumnoScalarWhereWithAggregatesInput | Prisma.HistorialAlumnoScalarWhereWithAggregatesInput[]
  OR?: Prisma.HistorialAlumnoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.HistorialAlumnoScalarWhereWithAggregatesInput | Prisma.HistorialAlumnoScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"HistorialAlumno"> | string
  periodoId?: Prisma.StringWithAggregatesFilter<"HistorialAlumno"> | string
  alumnoId?: Prisma.StringWithAggregatesFilter<"HistorialAlumno"> | string
  historialId?: Prisma.StringWithAggregatesFilter<"HistorialAlumno"> | string
  folio?: Prisma.StringNullableWithAggregatesFilter<"HistorialAlumno"> | string | null
  tipoExamen?: Prisma.StringNullableWithAggregatesFilter<"HistorialAlumno"> | string | null
  calificacionTexto?: Prisma.StringNullableWithAggregatesFilter<"HistorialAlumno"> | string | null
  aciertos?: Prisma.IntNullableWithAggregatesFilter<"HistorialAlumno"> | number | null
  totalReactivos?: Prisma.IntNullableWithAggregatesFilter<"HistorialAlumno"> | number | null
  fecha?: Prisma.DateTimeWithAggregatesFilter<"HistorialAlumno"> | Date | string
  metadata?: Prisma.StringNullableWithAggregatesFilter<"HistorialAlumno"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"HistorialAlumno"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"HistorialAlumno"> | Date | string
}

export type HistorialAlumnoCreateInput = {
  id?: string
  periodoId: string
  alumnoId: string
  historialId: string
  folio?: string | null
  tipoExamen?: string | null
  calificacionTexto?: string | null
  aciertos?: number | null
  totalReactivos?: number | null
  fecha?: Date | string
  metadata?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type HistorialAlumnoUncheckedCreateInput = {
  id?: string
  periodoId: string
  alumnoId: string
  historialId: string
  folio?: string | null
  tipoExamen?: string | null
  calificacionTexto?: string | null
  aciertos?: number | null
  totalReactivos?: number | null
  fecha?: Date | string
  metadata?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type HistorialAlumnoUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  periodoId?: Prisma.StringFieldUpdateOperationsInput | string
  alumnoId?: Prisma.StringFieldUpdateOperationsInput | string
  historialId?: Prisma.StringFieldUpdateOperationsInput | string
  folio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tipoExamen?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  calificacionTexto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aciertos?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  totalReactivos?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  metadata?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HistorialAlumnoUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  periodoId?: Prisma.StringFieldUpdateOperationsInput | string
  alumnoId?: Prisma.StringFieldUpdateOperationsInput | string
  historialId?: Prisma.StringFieldUpdateOperationsInput | string
  folio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tipoExamen?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  calificacionTexto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aciertos?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  totalReactivos?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  metadata?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HistorialAlumnoCreateManyInput = {
  id?: string
  periodoId: string
  alumnoId: string
  historialId: string
  folio?: string | null
  tipoExamen?: string | null
  calificacionTexto?: string | null
  aciertos?: number | null
  totalReactivos?: number | null
  fecha?: Date | string
  metadata?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type HistorialAlumnoUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  periodoId?: Prisma.StringFieldUpdateOperationsInput | string
  alumnoId?: Prisma.StringFieldUpdateOperationsInput | string
  historialId?: Prisma.StringFieldUpdateOperationsInput | string
  folio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tipoExamen?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  calificacionTexto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aciertos?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  totalReactivos?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  metadata?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HistorialAlumnoUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  periodoId?: Prisma.StringFieldUpdateOperationsInput | string
  alumnoId?: Prisma.StringFieldUpdateOperationsInput | string
  historialId?: Prisma.StringFieldUpdateOperationsInput | string
  folio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tipoExamen?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  calificacionTexto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  aciertos?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  totalReactivos?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fecha?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  metadata?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HistorialAlumnoPeriodoIdAlumnoIdHistorialIdCompoundUniqueInput = {
  periodoId: string
  alumnoId: string
  historialId: string
}

export type HistorialAlumnoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  periodoId?: Prisma.SortOrder
  alumnoId?: Prisma.SortOrder
  historialId?: Prisma.SortOrder
  folio?: Prisma.SortOrder
  tipoExamen?: Prisma.SortOrder
  calificacionTexto?: Prisma.SortOrder
  aciertos?: Prisma.SortOrder
  totalReactivos?: Prisma.SortOrder
  fecha?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type HistorialAlumnoAvgOrderByAggregateInput = {
  aciertos?: Prisma.SortOrder
  totalReactivos?: Prisma.SortOrder
}

export type HistorialAlumnoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  periodoId?: Prisma.SortOrder
  alumnoId?: Prisma.SortOrder
  historialId?: Prisma.SortOrder
  folio?: Prisma.SortOrder
  tipoExamen?: Prisma.SortOrder
  calificacionTexto?: Prisma.SortOrder
  aciertos?: Prisma.SortOrder
  totalReactivos?: Prisma.SortOrder
  fecha?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type HistorialAlumnoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  periodoId?: Prisma.SortOrder
  alumnoId?: Prisma.SortOrder
  historialId?: Prisma.SortOrder
  folio?: Prisma.SortOrder
  tipoExamen?: Prisma.SortOrder
  calificacionTexto?: Prisma.SortOrder
  aciertos?: Prisma.SortOrder
  totalReactivos?: Prisma.SortOrder
  fecha?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type HistorialAlumnoSumOrderByAggregateInput = {
  aciertos?: Prisma.SortOrder
  totalReactivos?: Prisma.SortOrder
}



export type HistorialAlumnoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  periodoId?: boolean
  alumnoId?: boolean
  historialId?: boolean
  folio?: boolean
  tipoExamen?: boolean
  calificacionTexto?: boolean
  aciertos?: boolean
  totalReactivos?: boolean
  fecha?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["historialAlumno"]>

export type HistorialAlumnoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  periodoId?: boolean
  alumnoId?: boolean
  historialId?: boolean
  folio?: boolean
  tipoExamen?: boolean
  calificacionTexto?: boolean
  aciertos?: boolean
  totalReactivos?: boolean
  fecha?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["historialAlumno"]>

export type HistorialAlumnoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  periodoId?: boolean
  alumnoId?: boolean
  historialId?: boolean
  folio?: boolean
  tipoExamen?: boolean
  calificacionTexto?: boolean
  aciertos?: boolean
  totalReactivos?: boolean
  fecha?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["historialAlumno"]>

export type HistorialAlumnoSelectScalar = {
  id?: boolean
  periodoId?: boolean
  alumnoId?: boolean
  historialId?: boolean
  folio?: boolean
  tipoExamen?: boolean
  calificacionTexto?: boolean
  aciertos?: boolean
  totalReactivos?: boolean
  fecha?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type HistorialAlumnoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "periodoId" | "alumnoId" | "historialId" | "folio" | "tipoExamen" | "calificacionTexto" | "aciertos" | "totalReactivos" | "fecha" | "metadata" | "createdAt" | "updatedAt", ExtArgs["result"]["historialAlumno"]>

export type $HistorialAlumnoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "HistorialAlumno"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    periodoId: string
    alumnoId: string
    historialId: string
    folio: string | null
    tipoExamen: string | null
    calificacionTexto: string | null
    aciertos: number | null
    totalReactivos: number | null
    fecha: Date
    metadata: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["historialAlumno"]>
  composites: {}
}

export type HistorialAlumnoGetPayload<S extends boolean | null | undefined | HistorialAlumnoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$HistorialAlumnoPayload, S>

export type HistorialAlumnoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<HistorialAlumnoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HistorialAlumnoCountAggregateInputType | true
  }

export interface HistorialAlumnoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['HistorialAlumno'], meta: { name: 'HistorialAlumno' } }
  /**
   * Find zero or one HistorialAlumno that matches the filter.
   * @param {HistorialAlumnoFindUniqueArgs} args - Arguments to find a HistorialAlumno
   * @example
   * // Get one HistorialAlumno
   * const historialAlumno = await prisma.historialAlumno.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends HistorialAlumnoFindUniqueArgs>(args: Prisma.SelectSubset<T, HistorialAlumnoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__HistorialAlumnoClient<runtime.Types.Result.GetResult<Prisma.$HistorialAlumnoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one HistorialAlumno that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {HistorialAlumnoFindUniqueOrThrowArgs} args - Arguments to find a HistorialAlumno
   * @example
   * // Get one HistorialAlumno
   * const historialAlumno = await prisma.historialAlumno.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends HistorialAlumnoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, HistorialAlumnoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__HistorialAlumnoClient<runtime.Types.Result.GetResult<Prisma.$HistorialAlumnoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first HistorialAlumno that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HistorialAlumnoFindFirstArgs} args - Arguments to find a HistorialAlumno
   * @example
   * // Get one HistorialAlumno
   * const historialAlumno = await prisma.historialAlumno.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends HistorialAlumnoFindFirstArgs>(args?: Prisma.SelectSubset<T, HistorialAlumnoFindFirstArgs<ExtArgs>>): Prisma.Prisma__HistorialAlumnoClient<runtime.Types.Result.GetResult<Prisma.$HistorialAlumnoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first HistorialAlumno that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HistorialAlumnoFindFirstOrThrowArgs} args - Arguments to find a HistorialAlumno
   * @example
   * // Get one HistorialAlumno
   * const historialAlumno = await prisma.historialAlumno.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends HistorialAlumnoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, HistorialAlumnoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__HistorialAlumnoClient<runtime.Types.Result.GetResult<Prisma.$HistorialAlumnoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more HistorialAlumnos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HistorialAlumnoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all HistorialAlumnos
   * const historialAlumnos = await prisma.historialAlumno.findMany()
   * 
   * // Get first 10 HistorialAlumnos
   * const historialAlumnos = await prisma.historialAlumno.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const historialAlumnoWithIdOnly = await prisma.historialAlumno.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends HistorialAlumnoFindManyArgs>(args?: Prisma.SelectSubset<T, HistorialAlumnoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HistorialAlumnoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a HistorialAlumno.
   * @param {HistorialAlumnoCreateArgs} args - Arguments to create a HistorialAlumno.
   * @example
   * // Create one HistorialAlumno
   * const HistorialAlumno = await prisma.historialAlumno.create({
   *   data: {
   *     // ... data to create a HistorialAlumno
   *   }
   * })
   * 
   */
  create<T extends HistorialAlumnoCreateArgs>(args: Prisma.SelectSubset<T, HistorialAlumnoCreateArgs<ExtArgs>>): Prisma.Prisma__HistorialAlumnoClient<runtime.Types.Result.GetResult<Prisma.$HistorialAlumnoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many HistorialAlumnos.
   * @param {HistorialAlumnoCreateManyArgs} args - Arguments to create many HistorialAlumnos.
   * @example
   * // Create many HistorialAlumnos
   * const historialAlumno = await prisma.historialAlumno.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends HistorialAlumnoCreateManyArgs>(args?: Prisma.SelectSubset<T, HistorialAlumnoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many HistorialAlumnos and returns the data saved in the database.
   * @param {HistorialAlumnoCreateManyAndReturnArgs} args - Arguments to create many HistorialAlumnos.
   * @example
   * // Create many HistorialAlumnos
   * const historialAlumno = await prisma.historialAlumno.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many HistorialAlumnos and only return the `id`
   * const historialAlumnoWithIdOnly = await prisma.historialAlumno.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends HistorialAlumnoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, HistorialAlumnoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HistorialAlumnoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a HistorialAlumno.
   * @param {HistorialAlumnoDeleteArgs} args - Arguments to delete one HistorialAlumno.
   * @example
   * // Delete one HistorialAlumno
   * const HistorialAlumno = await prisma.historialAlumno.delete({
   *   where: {
   *     // ... filter to delete one HistorialAlumno
   *   }
   * })
   * 
   */
  delete<T extends HistorialAlumnoDeleteArgs>(args: Prisma.SelectSubset<T, HistorialAlumnoDeleteArgs<ExtArgs>>): Prisma.Prisma__HistorialAlumnoClient<runtime.Types.Result.GetResult<Prisma.$HistorialAlumnoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one HistorialAlumno.
   * @param {HistorialAlumnoUpdateArgs} args - Arguments to update one HistorialAlumno.
   * @example
   * // Update one HistorialAlumno
   * const historialAlumno = await prisma.historialAlumno.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends HistorialAlumnoUpdateArgs>(args: Prisma.SelectSubset<T, HistorialAlumnoUpdateArgs<ExtArgs>>): Prisma.Prisma__HistorialAlumnoClient<runtime.Types.Result.GetResult<Prisma.$HistorialAlumnoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more HistorialAlumnos.
   * @param {HistorialAlumnoDeleteManyArgs} args - Arguments to filter HistorialAlumnos to delete.
   * @example
   * // Delete a few HistorialAlumnos
   * const { count } = await prisma.historialAlumno.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends HistorialAlumnoDeleteManyArgs>(args?: Prisma.SelectSubset<T, HistorialAlumnoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more HistorialAlumnos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HistorialAlumnoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many HistorialAlumnos
   * const historialAlumno = await prisma.historialAlumno.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends HistorialAlumnoUpdateManyArgs>(args: Prisma.SelectSubset<T, HistorialAlumnoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more HistorialAlumnos and returns the data updated in the database.
   * @param {HistorialAlumnoUpdateManyAndReturnArgs} args - Arguments to update many HistorialAlumnos.
   * @example
   * // Update many HistorialAlumnos
   * const historialAlumno = await prisma.historialAlumno.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more HistorialAlumnos and only return the `id`
   * const historialAlumnoWithIdOnly = await prisma.historialAlumno.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends HistorialAlumnoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, HistorialAlumnoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HistorialAlumnoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one HistorialAlumno.
   * @param {HistorialAlumnoUpsertArgs} args - Arguments to update or create a HistorialAlumno.
   * @example
   * // Update or create a HistorialAlumno
   * const historialAlumno = await prisma.historialAlumno.upsert({
   *   create: {
   *     // ... data to create a HistorialAlumno
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the HistorialAlumno we want to update
   *   }
   * })
   */
  upsert<T extends HistorialAlumnoUpsertArgs>(args: Prisma.SelectSubset<T, HistorialAlumnoUpsertArgs<ExtArgs>>): Prisma.Prisma__HistorialAlumnoClient<runtime.Types.Result.GetResult<Prisma.$HistorialAlumnoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of HistorialAlumnos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HistorialAlumnoCountArgs} args - Arguments to filter HistorialAlumnos to count.
   * @example
   * // Count the number of HistorialAlumnos
   * const count = await prisma.historialAlumno.count({
   *   where: {
   *     // ... the filter for the HistorialAlumnos we want to count
   *   }
   * })
  **/
  count<T extends HistorialAlumnoCountArgs>(
    args?: Prisma.Subset<T, HistorialAlumnoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HistorialAlumnoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a HistorialAlumno.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HistorialAlumnoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HistorialAlumnoAggregateArgs>(args: Prisma.Subset<T, HistorialAlumnoAggregateArgs>): Prisma.PrismaPromise<GetHistorialAlumnoAggregateType<T>>

  /**
   * Group by HistorialAlumno.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HistorialAlumnoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends HistorialAlumnoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: HistorialAlumnoGroupByArgs['orderBy'] }
      : { orderBy?: HistorialAlumnoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, HistorialAlumnoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHistorialAlumnoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the HistorialAlumno model
 */
readonly fields: HistorialAlumnoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for HistorialAlumno.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__HistorialAlumnoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the HistorialAlumno model
 */
export interface HistorialAlumnoFieldRefs {
  readonly id: Prisma.FieldRef<"HistorialAlumno", 'String'>
  readonly periodoId: Prisma.FieldRef<"HistorialAlumno", 'String'>
  readonly alumnoId: Prisma.FieldRef<"HistorialAlumno", 'String'>
  readonly historialId: Prisma.FieldRef<"HistorialAlumno", 'String'>
  readonly folio: Prisma.FieldRef<"HistorialAlumno", 'String'>
  readonly tipoExamen: Prisma.FieldRef<"HistorialAlumno", 'String'>
  readonly calificacionTexto: Prisma.FieldRef<"HistorialAlumno", 'String'>
  readonly aciertos: Prisma.FieldRef<"HistorialAlumno", 'Int'>
  readonly totalReactivos: Prisma.FieldRef<"HistorialAlumno", 'Int'>
  readonly fecha: Prisma.FieldRef<"HistorialAlumno", 'DateTime'>
  readonly metadata: Prisma.FieldRef<"HistorialAlumno", 'String'>
  readonly createdAt: Prisma.FieldRef<"HistorialAlumno", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"HistorialAlumno", 'DateTime'>
}
    

// Custom InputTypes
/**
 * HistorialAlumno findUnique
 */
export type HistorialAlumnoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HistorialAlumno
   */
  select?: Prisma.HistorialAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HistorialAlumno
   */
  omit?: Prisma.HistorialAlumnoOmit<ExtArgs> | null
  /**
   * Filter, which HistorialAlumno to fetch.
   */
  where: Prisma.HistorialAlumnoWhereUniqueInput
}

/**
 * HistorialAlumno findUniqueOrThrow
 */
export type HistorialAlumnoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HistorialAlumno
   */
  select?: Prisma.HistorialAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HistorialAlumno
   */
  omit?: Prisma.HistorialAlumnoOmit<ExtArgs> | null
  /**
   * Filter, which HistorialAlumno to fetch.
   */
  where: Prisma.HistorialAlumnoWhereUniqueInput
}

/**
 * HistorialAlumno findFirst
 */
export type HistorialAlumnoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HistorialAlumno
   */
  select?: Prisma.HistorialAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HistorialAlumno
   */
  omit?: Prisma.HistorialAlumnoOmit<ExtArgs> | null
  /**
   * Filter, which HistorialAlumno to fetch.
   */
  where?: Prisma.HistorialAlumnoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HistorialAlumnos to fetch.
   */
  orderBy?: Prisma.HistorialAlumnoOrderByWithRelationInput | Prisma.HistorialAlumnoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for HistorialAlumnos.
   */
  cursor?: Prisma.HistorialAlumnoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HistorialAlumnos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HistorialAlumnos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of HistorialAlumnos.
   */
  distinct?: Prisma.HistorialAlumnoScalarFieldEnum | Prisma.HistorialAlumnoScalarFieldEnum[]
}

/**
 * HistorialAlumno findFirstOrThrow
 */
export type HistorialAlumnoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HistorialAlumno
   */
  select?: Prisma.HistorialAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HistorialAlumno
   */
  omit?: Prisma.HistorialAlumnoOmit<ExtArgs> | null
  /**
   * Filter, which HistorialAlumno to fetch.
   */
  where?: Prisma.HistorialAlumnoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HistorialAlumnos to fetch.
   */
  orderBy?: Prisma.HistorialAlumnoOrderByWithRelationInput | Prisma.HistorialAlumnoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for HistorialAlumnos.
   */
  cursor?: Prisma.HistorialAlumnoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HistorialAlumnos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HistorialAlumnos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of HistorialAlumnos.
   */
  distinct?: Prisma.HistorialAlumnoScalarFieldEnum | Prisma.HistorialAlumnoScalarFieldEnum[]
}

/**
 * HistorialAlumno findMany
 */
export type HistorialAlumnoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HistorialAlumno
   */
  select?: Prisma.HistorialAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HistorialAlumno
   */
  omit?: Prisma.HistorialAlumnoOmit<ExtArgs> | null
  /**
   * Filter, which HistorialAlumnos to fetch.
   */
  where?: Prisma.HistorialAlumnoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HistorialAlumnos to fetch.
   */
  orderBy?: Prisma.HistorialAlumnoOrderByWithRelationInput | Prisma.HistorialAlumnoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing HistorialAlumnos.
   */
  cursor?: Prisma.HistorialAlumnoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HistorialAlumnos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HistorialAlumnos.
   */
  skip?: number
  distinct?: Prisma.HistorialAlumnoScalarFieldEnum | Prisma.HistorialAlumnoScalarFieldEnum[]
}

/**
 * HistorialAlumno create
 */
export type HistorialAlumnoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HistorialAlumno
   */
  select?: Prisma.HistorialAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HistorialAlumno
   */
  omit?: Prisma.HistorialAlumnoOmit<ExtArgs> | null
  /**
   * The data needed to create a HistorialAlumno.
   */
  data: Prisma.XOR<Prisma.HistorialAlumnoCreateInput, Prisma.HistorialAlumnoUncheckedCreateInput>
}

/**
 * HistorialAlumno createMany
 */
export type HistorialAlumnoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many HistorialAlumnos.
   */
  data: Prisma.HistorialAlumnoCreateManyInput | Prisma.HistorialAlumnoCreateManyInput[]
}

/**
 * HistorialAlumno createManyAndReturn
 */
export type HistorialAlumnoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HistorialAlumno
   */
  select?: Prisma.HistorialAlumnoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the HistorialAlumno
   */
  omit?: Prisma.HistorialAlumnoOmit<ExtArgs> | null
  /**
   * The data used to create many HistorialAlumnos.
   */
  data: Prisma.HistorialAlumnoCreateManyInput | Prisma.HistorialAlumnoCreateManyInput[]
}

/**
 * HistorialAlumno update
 */
export type HistorialAlumnoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HistorialAlumno
   */
  select?: Prisma.HistorialAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HistorialAlumno
   */
  omit?: Prisma.HistorialAlumnoOmit<ExtArgs> | null
  /**
   * The data needed to update a HistorialAlumno.
   */
  data: Prisma.XOR<Prisma.HistorialAlumnoUpdateInput, Prisma.HistorialAlumnoUncheckedUpdateInput>
  /**
   * Choose, which HistorialAlumno to update.
   */
  where: Prisma.HistorialAlumnoWhereUniqueInput
}

/**
 * HistorialAlumno updateMany
 */
export type HistorialAlumnoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update HistorialAlumnos.
   */
  data: Prisma.XOR<Prisma.HistorialAlumnoUpdateManyMutationInput, Prisma.HistorialAlumnoUncheckedUpdateManyInput>
  /**
   * Filter which HistorialAlumnos to update
   */
  where?: Prisma.HistorialAlumnoWhereInput
  /**
   * Limit how many HistorialAlumnos to update.
   */
  limit?: number
}

/**
 * HistorialAlumno updateManyAndReturn
 */
export type HistorialAlumnoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HistorialAlumno
   */
  select?: Prisma.HistorialAlumnoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the HistorialAlumno
   */
  omit?: Prisma.HistorialAlumnoOmit<ExtArgs> | null
  /**
   * The data used to update HistorialAlumnos.
   */
  data: Prisma.XOR<Prisma.HistorialAlumnoUpdateManyMutationInput, Prisma.HistorialAlumnoUncheckedUpdateManyInput>
  /**
   * Filter which HistorialAlumnos to update
   */
  where?: Prisma.HistorialAlumnoWhereInput
  /**
   * Limit how many HistorialAlumnos to update.
   */
  limit?: number
}

/**
 * HistorialAlumno upsert
 */
export type HistorialAlumnoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HistorialAlumno
   */
  select?: Prisma.HistorialAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HistorialAlumno
   */
  omit?: Prisma.HistorialAlumnoOmit<ExtArgs> | null
  /**
   * The filter to search for the HistorialAlumno to update in case it exists.
   */
  where: Prisma.HistorialAlumnoWhereUniqueInput
  /**
   * In case the HistorialAlumno found by the `where` argument doesn't exist, create a new HistorialAlumno with this data.
   */
  create: Prisma.XOR<Prisma.HistorialAlumnoCreateInput, Prisma.HistorialAlumnoUncheckedCreateInput>
  /**
   * In case the HistorialAlumno was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.HistorialAlumnoUpdateInput, Prisma.HistorialAlumnoUncheckedUpdateInput>
}

/**
 * HistorialAlumno delete
 */
export type HistorialAlumnoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HistorialAlumno
   */
  select?: Prisma.HistorialAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HistorialAlumno
   */
  omit?: Prisma.HistorialAlumnoOmit<ExtArgs> | null
  /**
   * Filter which HistorialAlumno to delete.
   */
  where: Prisma.HistorialAlumnoWhereUniqueInput
}

/**
 * HistorialAlumno deleteMany
 */
export type HistorialAlumnoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which HistorialAlumnos to delete
   */
  where?: Prisma.HistorialAlumnoWhereInput
  /**
   * Limit how many HistorialAlumnos to delete.
   */
  limit?: number
}

/**
 * HistorialAlumno without action
 */
export type HistorialAlumnoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HistorialAlumno
   */
  select?: Prisma.HistorialAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HistorialAlumno
   */
  omit?: Prisma.HistorialAlumnoOmit<ExtArgs> | null
}
