
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MateriaAlumno` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model MateriaAlumno
 * 
 */
export type MateriaAlumnoModel = runtime.Types.Result.DefaultSelection<Prisma.$MateriaAlumnoPayload>

export type AggregateMateriaAlumno = {
  _count: MateriaAlumnoCountAggregateOutputType | null
  _min: MateriaAlumnoMinAggregateOutputType | null
  _max: MateriaAlumnoMaxAggregateOutputType | null
}

export type MateriaAlumnoMinAggregateOutputType = {
  id: string | null
  periodoId: string | null
  alumnoId: string | null
  materiaId: string | null
  nombre: string | null
  docente: string | null
  estado: string | null
  metadata: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MateriaAlumnoMaxAggregateOutputType = {
  id: string | null
  periodoId: string | null
  alumnoId: string | null
  materiaId: string | null
  nombre: string | null
  docente: string | null
  estado: string | null
  metadata: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MateriaAlumnoCountAggregateOutputType = {
  id: number
  periodoId: number
  alumnoId: number
  materiaId: number
  nombre: number
  docente: number
  estado: number
  metadata: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type MateriaAlumnoMinAggregateInputType = {
  id?: true
  periodoId?: true
  alumnoId?: true
  materiaId?: true
  nombre?: true
  docente?: true
  estado?: true
  metadata?: true
  createdAt?: true
  updatedAt?: true
}

export type MateriaAlumnoMaxAggregateInputType = {
  id?: true
  periodoId?: true
  alumnoId?: true
  materiaId?: true
  nombre?: true
  docente?: true
  estado?: true
  metadata?: true
  createdAt?: true
  updatedAt?: true
}

export type MateriaAlumnoCountAggregateInputType = {
  id?: true
  periodoId?: true
  alumnoId?: true
  materiaId?: true
  nombre?: true
  docente?: true
  estado?: true
  metadata?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type MateriaAlumnoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MateriaAlumno to aggregate.
   */
  where?: Prisma.MateriaAlumnoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MateriaAlumnos to fetch.
   */
  orderBy?: Prisma.MateriaAlumnoOrderByWithRelationInput | Prisma.MateriaAlumnoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MateriaAlumnoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MateriaAlumnos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MateriaAlumnos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MateriaAlumnos
  **/
  _count?: true | MateriaAlumnoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MateriaAlumnoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MateriaAlumnoMaxAggregateInputType
}

export type GetMateriaAlumnoAggregateType<T extends MateriaAlumnoAggregateArgs> = {
      [P in keyof T & keyof AggregateMateriaAlumno]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMateriaAlumno[P]>
    : Prisma.GetScalarType<T[P], AggregateMateriaAlumno[P]>
}




export type MateriaAlumnoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MateriaAlumnoWhereInput
  orderBy?: Prisma.MateriaAlumnoOrderByWithAggregationInput | Prisma.MateriaAlumnoOrderByWithAggregationInput[]
  by: Prisma.MateriaAlumnoScalarFieldEnum[] | Prisma.MateriaAlumnoScalarFieldEnum
  having?: Prisma.MateriaAlumnoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MateriaAlumnoCountAggregateInputType | true
  _min?: MateriaAlumnoMinAggregateInputType
  _max?: MateriaAlumnoMaxAggregateInputType
}

export type MateriaAlumnoGroupByOutputType = {
  id: string
  periodoId: string
  alumnoId: string
  materiaId: string
  nombre: string
  docente: string | null
  estado: string
  metadata: string | null
  createdAt: Date
  updatedAt: Date
  _count: MateriaAlumnoCountAggregateOutputType | null
  _min: MateriaAlumnoMinAggregateOutputType | null
  _max: MateriaAlumnoMaxAggregateOutputType | null
}

type GetMateriaAlumnoGroupByPayload<T extends MateriaAlumnoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MateriaAlumnoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MateriaAlumnoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MateriaAlumnoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MateriaAlumnoGroupByOutputType[P]>
      }
    >
  >



export type MateriaAlumnoWhereInput = {
  AND?: Prisma.MateriaAlumnoWhereInput | Prisma.MateriaAlumnoWhereInput[]
  OR?: Prisma.MateriaAlumnoWhereInput[]
  NOT?: Prisma.MateriaAlumnoWhereInput | Prisma.MateriaAlumnoWhereInput[]
  id?: Prisma.StringFilter<"MateriaAlumno"> | string
  periodoId?: Prisma.StringFilter<"MateriaAlumno"> | string
  alumnoId?: Prisma.StringFilter<"MateriaAlumno"> | string
  materiaId?: Prisma.StringFilter<"MateriaAlumno"> | string
  nombre?: Prisma.StringFilter<"MateriaAlumno"> | string
  docente?: Prisma.StringNullableFilter<"MateriaAlumno"> | string | null
  estado?: Prisma.StringFilter<"MateriaAlumno"> | string
  metadata?: Prisma.StringNullableFilter<"MateriaAlumno"> | string | null
  createdAt?: Prisma.DateTimeFilter<"MateriaAlumno"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MateriaAlumno"> | Date | string
}

export type MateriaAlumnoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  periodoId?: Prisma.SortOrder
  alumnoId?: Prisma.SortOrder
  materiaId?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  docente?: Prisma.SortOrderInput | Prisma.SortOrder
  estado?: Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MateriaAlumnoWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  periodoId_alumnoId_materiaId?: Prisma.MateriaAlumnoPeriodoIdAlumnoIdMateriaIdCompoundUniqueInput
  AND?: Prisma.MateriaAlumnoWhereInput | Prisma.MateriaAlumnoWhereInput[]
  OR?: Prisma.MateriaAlumnoWhereInput[]
  NOT?: Prisma.MateriaAlumnoWhereInput | Prisma.MateriaAlumnoWhereInput[]
  periodoId?: Prisma.StringFilter<"MateriaAlumno"> | string
  alumnoId?: Prisma.StringFilter<"MateriaAlumno"> | string
  materiaId?: Prisma.StringFilter<"MateriaAlumno"> | string
  nombre?: Prisma.StringFilter<"MateriaAlumno"> | string
  docente?: Prisma.StringNullableFilter<"MateriaAlumno"> | string | null
  estado?: Prisma.StringFilter<"MateriaAlumno"> | string
  metadata?: Prisma.StringNullableFilter<"MateriaAlumno"> | string | null
  createdAt?: Prisma.DateTimeFilter<"MateriaAlumno"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MateriaAlumno"> | Date | string
}, "id" | "periodoId_alumnoId_materiaId">

export type MateriaAlumnoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  periodoId?: Prisma.SortOrder
  alumnoId?: Prisma.SortOrder
  materiaId?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  docente?: Prisma.SortOrderInput | Prisma.SortOrder
  estado?: Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.MateriaAlumnoCountOrderByAggregateInput
  _max?: Prisma.MateriaAlumnoMaxOrderByAggregateInput
  _min?: Prisma.MateriaAlumnoMinOrderByAggregateInput
}

export type MateriaAlumnoScalarWhereWithAggregatesInput = {
  AND?: Prisma.MateriaAlumnoScalarWhereWithAggregatesInput | Prisma.MateriaAlumnoScalarWhereWithAggregatesInput[]
  OR?: Prisma.MateriaAlumnoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MateriaAlumnoScalarWhereWithAggregatesInput | Prisma.MateriaAlumnoScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"MateriaAlumno"> | string
  periodoId?: Prisma.StringWithAggregatesFilter<"MateriaAlumno"> | string
  alumnoId?: Prisma.StringWithAggregatesFilter<"MateriaAlumno"> | string
  materiaId?: Prisma.StringWithAggregatesFilter<"MateriaAlumno"> | string
  nombre?: Prisma.StringWithAggregatesFilter<"MateriaAlumno"> | string
  docente?: Prisma.StringNullableWithAggregatesFilter<"MateriaAlumno"> | string | null
  estado?: Prisma.StringWithAggregatesFilter<"MateriaAlumno"> | string
  metadata?: Prisma.StringNullableWithAggregatesFilter<"MateriaAlumno"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"MateriaAlumno"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"MateriaAlumno"> | Date | string
}

export type MateriaAlumnoCreateInput = {
  id?: string
  periodoId: string
  alumnoId: string
  materiaId: string
  nombre: string
  docente?: string | null
  estado?: string
  metadata?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MateriaAlumnoUncheckedCreateInput = {
  id?: string
  periodoId: string
  alumnoId: string
  materiaId: string
  nombre: string
  docente?: string | null
  estado?: string
  metadata?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MateriaAlumnoUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  periodoId?: Prisma.StringFieldUpdateOperationsInput | string
  alumnoId?: Prisma.StringFieldUpdateOperationsInput | string
  materiaId?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  docente?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MateriaAlumnoUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  periodoId?: Prisma.StringFieldUpdateOperationsInput | string
  alumnoId?: Prisma.StringFieldUpdateOperationsInput | string
  materiaId?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  docente?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MateriaAlumnoCreateManyInput = {
  id?: string
  periodoId: string
  alumnoId: string
  materiaId: string
  nombre: string
  docente?: string | null
  estado?: string
  metadata?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MateriaAlumnoUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  periodoId?: Prisma.StringFieldUpdateOperationsInput | string
  alumnoId?: Prisma.StringFieldUpdateOperationsInput | string
  materiaId?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  docente?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MateriaAlumnoUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  periodoId?: Prisma.StringFieldUpdateOperationsInput | string
  alumnoId?: Prisma.StringFieldUpdateOperationsInput | string
  materiaId?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  docente?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  metadata?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MateriaAlumnoPeriodoIdAlumnoIdMateriaIdCompoundUniqueInput = {
  periodoId: string
  alumnoId: string
  materiaId: string
}

export type MateriaAlumnoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  periodoId?: Prisma.SortOrder
  alumnoId?: Prisma.SortOrder
  materiaId?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  docente?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MateriaAlumnoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  periodoId?: Prisma.SortOrder
  alumnoId?: Prisma.SortOrder
  materiaId?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  docente?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MateriaAlumnoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  periodoId?: Prisma.SortOrder
  alumnoId?: Prisma.SortOrder
  materiaId?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  docente?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}



export type MateriaAlumnoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  periodoId?: boolean
  alumnoId?: boolean
  materiaId?: boolean
  nombre?: boolean
  docente?: boolean
  estado?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["materiaAlumno"]>

export type MateriaAlumnoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  periodoId?: boolean
  alumnoId?: boolean
  materiaId?: boolean
  nombre?: boolean
  docente?: boolean
  estado?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["materiaAlumno"]>

export type MateriaAlumnoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  periodoId?: boolean
  alumnoId?: boolean
  materiaId?: boolean
  nombre?: boolean
  docente?: boolean
  estado?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["materiaAlumno"]>

export type MateriaAlumnoSelectScalar = {
  id?: boolean
  periodoId?: boolean
  alumnoId?: boolean
  materiaId?: boolean
  nombre?: boolean
  docente?: boolean
  estado?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type MateriaAlumnoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "periodoId" | "alumnoId" | "materiaId" | "nombre" | "docente" | "estado" | "metadata" | "createdAt" | "updatedAt", ExtArgs["result"]["materiaAlumno"]>

export type $MateriaAlumnoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MateriaAlumno"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    periodoId: string
    alumnoId: string
    materiaId: string
    nombre: string
    docente: string | null
    estado: string
    metadata: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["materiaAlumno"]>
  composites: {}
}

export type MateriaAlumnoGetPayload<S extends boolean | null | undefined | MateriaAlumnoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MateriaAlumnoPayload, S>

export type MateriaAlumnoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MateriaAlumnoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MateriaAlumnoCountAggregateInputType | true
  }

export interface MateriaAlumnoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MateriaAlumno'], meta: { name: 'MateriaAlumno' } }
  /**
   * Find zero or one MateriaAlumno that matches the filter.
   * @param {MateriaAlumnoFindUniqueArgs} args - Arguments to find a MateriaAlumno
   * @example
   * // Get one MateriaAlumno
   * const materiaAlumno = await prisma.materiaAlumno.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MateriaAlumnoFindUniqueArgs>(args: Prisma.SelectSubset<T, MateriaAlumnoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MateriaAlumnoClient<runtime.Types.Result.GetResult<Prisma.$MateriaAlumnoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MateriaAlumno that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MateriaAlumnoFindUniqueOrThrowArgs} args - Arguments to find a MateriaAlumno
   * @example
   * // Get one MateriaAlumno
   * const materiaAlumno = await prisma.materiaAlumno.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MateriaAlumnoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MateriaAlumnoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MateriaAlumnoClient<runtime.Types.Result.GetResult<Prisma.$MateriaAlumnoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MateriaAlumno that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MateriaAlumnoFindFirstArgs} args - Arguments to find a MateriaAlumno
   * @example
   * // Get one MateriaAlumno
   * const materiaAlumno = await prisma.materiaAlumno.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MateriaAlumnoFindFirstArgs>(args?: Prisma.SelectSubset<T, MateriaAlumnoFindFirstArgs<ExtArgs>>): Prisma.Prisma__MateriaAlumnoClient<runtime.Types.Result.GetResult<Prisma.$MateriaAlumnoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MateriaAlumno that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MateriaAlumnoFindFirstOrThrowArgs} args - Arguments to find a MateriaAlumno
   * @example
   * // Get one MateriaAlumno
   * const materiaAlumno = await prisma.materiaAlumno.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MateriaAlumnoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MateriaAlumnoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MateriaAlumnoClient<runtime.Types.Result.GetResult<Prisma.$MateriaAlumnoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MateriaAlumnos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MateriaAlumnoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MateriaAlumnos
   * const materiaAlumnos = await prisma.materiaAlumno.findMany()
   * 
   * // Get first 10 MateriaAlumnos
   * const materiaAlumnos = await prisma.materiaAlumno.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const materiaAlumnoWithIdOnly = await prisma.materiaAlumno.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MateriaAlumnoFindManyArgs>(args?: Prisma.SelectSubset<T, MateriaAlumnoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MateriaAlumnoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MateriaAlumno.
   * @param {MateriaAlumnoCreateArgs} args - Arguments to create a MateriaAlumno.
   * @example
   * // Create one MateriaAlumno
   * const MateriaAlumno = await prisma.materiaAlumno.create({
   *   data: {
   *     // ... data to create a MateriaAlumno
   *   }
   * })
   * 
   */
  create<T extends MateriaAlumnoCreateArgs>(args: Prisma.SelectSubset<T, MateriaAlumnoCreateArgs<ExtArgs>>): Prisma.Prisma__MateriaAlumnoClient<runtime.Types.Result.GetResult<Prisma.$MateriaAlumnoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MateriaAlumnos.
   * @param {MateriaAlumnoCreateManyArgs} args - Arguments to create many MateriaAlumnos.
   * @example
   * // Create many MateriaAlumnos
   * const materiaAlumno = await prisma.materiaAlumno.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MateriaAlumnoCreateManyArgs>(args?: Prisma.SelectSubset<T, MateriaAlumnoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MateriaAlumnos and returns the data saved in the database.
   * @param {MateriaAlumnoCreateManyAndReturnArgs} args - Arguments to create many MateriaAlumnos.
   * @example
   * // Create many MateriaAlumnos
   * const materiaAlumno = await prisma.materiaAlumno.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MateriaAlumnos and only return the `id`
   * const materiaAlumnoWithIdOnly = await prisma.materiaAlumno.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MateriaAlumnoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MateriaAlumnoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MateriaAlumnoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MateriaAlumno.
   * @param {MateriaAlumnoDeleteArgs} args - Arguments to delete one MateriaAlumno.
   * @example
   * // Delete one MateriaAlumno
   * const MateriaAlumno = await prisma.materiaAlumno.delete({
   *   where: {
   *     // ... filter to delete one MateriaAlumno
   *   }
   * })
   * 
   */
  delete<T extends MateriaAlumnoDeleteArgs>(args: Prisma.SelectSubset<T, MateriaAlumnoDeleteArgs<ExtArgs>>): Prisma.Prisma__MateriaAlumnoClient<runtime.Types.Result.GetResult<Prisma.$MateriaAlumnoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MateriaAlumno.
   * @param {MateriaAlumnoUpdateArgs} args - Arguments to update one MateriaAlumno.
   * @example
   * // Update one MateriaAlumno
   * const materiaAlumno = await prisma.materiaAlumno.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MateriaAlumnoUpdateArgs>(args: Prisma.SelectSubset<T, MateriaAlumnoUpdateArgs<ExtArgs>>): Prisma.Prisma__MateriaAlumnoClient<runtime.Types.Result.GetResult<Prisma.$MateriaAlumnoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MateriaAlumnos.
   * @param {MateriaAlumnoDeleteManyArgs} args - Arguments to filter MateriaAlumnos to delete.
   * @example
   * // Delete a few MateriaAlumnos
   * const { count } = await prisma.materiaAlumno.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MateriaAlumnoDeleteManyArgs>(args?: Prisma.SelectSubset<T, MateriaAlumnoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MateriaAlumnos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MateriaAlumnoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MateriaAlumnos
   * const materiaAlumno = await prisma.materiaAlumno.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MateriaAlumnoUpdateManyArgs>(args: Prisma.SelectSubset<T, MateriaAlumnoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MateriaAlumnos and returns the data updated in the database.
   * @param {MateriaAlumnoUpdateManyAndReturnArgs} args - Arguments to update many MateriaAlumnos.
   * @example
   * // Update many MateriaAlumnos
   * const materiaAlumno = await prisma.materiaAlumno.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MateriaAlumnos and only return the `id`
   * const materiaAlumnoWithIdOnly = await prisma.materiaAlumno.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MateriaAlumnoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MateriaAlumnoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MateriaAlumnoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MateriaAlumno.
   * @param {MateriaAlumnoUpsertArgs} args - Arguments to update or create a MateriaAlumno.
   * @example
   * // Update or create a MateriaAlumno
   * const materiaAlumno = await prisma.materiaAlumno.upsert({
   *   create: {
   *     // ... data to create a MateriaAlumno
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MateriaAlumno we want to update
   *   }
   * })
   */
  upsert<T extends MateriaAlumnoUpsertArgs>(args: Prisma.SelectSubset<T, MateriaAlumnoUpsertArgs<ExtArgs>>): Prisma.Prisma__MateriaAlumnoClient<runtime.Types.Result.GetResult<Prisma.$MateriaAlumnoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MateriaAlumnos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MateriaAlumnoCountArgs} args - Arguments to filter MateriaAlumnos to count.
   * @example
   * // Count the number of MateriaAlumnos
   * const count = await prisma.materiaAlumno.count({
   *   where: {
   *     // ... the filter for the MateriaAlumnos we want to count
   *   }
   * })
  **/
  count<T extends MateriaAlumnoCountArgs>(
    args?: Prisma.Subset<T, MateriaAlumnoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MateriaAlumnoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MateriaAlumno.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MateriaAlumnoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MateriaAlumnoAggregateArgs>(args: Prisma.Subset<T, MateriaAlumnoAggregateArgs>): Prisma.PrismaPromise<GetMateriaAlumnoAggregateType<T>>

  /**
   * Group by MateriaAlumno.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MateriaAlumnoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MateriaAlumnoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MateriaAlumnoGroupByArgs['orderBy'] }
      : { orderBy?: MateriaAlumnoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MateriaAlumnoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMateriaAlumnoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MateriaAlumno model
 */
readonly fields: MateriaAlumnoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MateriaAlumno.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MateriaAlumnoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MateriaAlumno model
 */
export interface MateriaAlumnoFieldRefs {
  readonly id: Prisma.FieldRef<"MateriaAlumno", 'String'>
  readonly periodoId: Prisma.FieldRef<"MateriaAlumno", 'String'>
  readonly alumnoId: Prisma.FieldRef<"MateriaAlumno", 'String'>
  readonly materiaId: Prisma.FieldRef<"MateriaAlumno", 'String'>
  readonly nombre: Prisma.FieldRef<"MateriaAlumno", 'String'>
  readonly docente: Prisma.FieldRef<"MateriaAlumno", 'String'>
  readonly estado: Prisma.FieldRef<"MateriaAlumno", 'String'>
  readonly metadata: Prisma.FieldRef<"MateriaAlumno", 'String'>
  readonly createdAt: Prisma.FieldRef<"MateriaAlumno", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"MateriaAlumno", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MateriaAlumno findUnique
 */
export type MateriaAlumnoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MateriaAlumno
   */
  select?: Prisma.MateriaAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MateriaAlumno
   */
  omit?: Prisma.MateriaAlumnoOmit<ExtArgs> | null
  /**
   * Filter, which MateriaAlumno to fetch.
   */
  where: Prisma.MateriaAlumnoWhereUniqueInput
}

/**
 * MateriaAlumno findUniqueOrThrow
 */
export type MateriaAlumnoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MateriaAlumno
   */
  select?: Prisma.MateriaAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MateriaAlumno
   */
  omit?: Prisma.MateriaAlumnoOmit<ExtArgs> | null
  /**
   * Filter, which MateriaAlumno to fetch.
   */
  where: Prisma.MateriaAlumnoWhereUniqueInput
}

/**
 * MateriaAlumno findFirst
 */
export type MateriaAlumnoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MateriaAlumno
   */
  select?: Prisma.MateriaAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MateriaAlumno
   */
  omit?: Prisma.MateriaAlumnoOmit<ExtArgs> | null
  /**
   * Filter, which MateriaAlumno to fetch.
   */
  where?: Prisma.MateriaAlumnoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MateriaAlumnos to fetch.
   */
  orderBy?: Prisma.MateriaAlumnoOrderByWithRelationInput | Prisma.MateriaAlumnoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MateriaAlumnos.
   */
  cursor?: Prisma.MateriaAlumnoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MateriaAlumnos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MateriaAlumnos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MateriaAlumnos.
   */
  distinct?: Prisma.MateriaAlumnoScalarFieldEnum | Prisma.MateriaAlumnoScalarFieldEnum[]
}

/**
 * MateriaAlumno findFirstOrThrow
 */
export type MateriaAlumnoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MateriaAlumno
   */
  select?: Prisma.MateriaAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MateriaAlumno
   */
  omit?: Prisma.MateriaAlumnoOmit<ExtArgs> | null
  /**
   * Filter, which MateriaAlumno to fetch.
   */
  where?: Prisma.MateriaAlumnoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MateriaAlumnos to fetch.
   */
  orderBy?: Prisma.MateriaAlumnoOrderByWithRelationInput | Prisma.MateriaAlumnoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MateriaAlumnos.
   */
  cursor?: Prisma.MateriaAlumnoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MateriaAlumnos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MateriaAlumnos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MateriaAlumnos.
   */
  distinct?: Prisma.MateriaAlumnoScalarFieldEnum | Prisma.MateriaAlumnoScalarFieldEnum[]
}

/**
 * MateriaAlumno findMany
 */
export type MateriaAlumnoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MateriaAlumno
   */
  select?: Prisma.MateriaAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MateriaAlumno
   */
  omit?: Prisma.MateriaAlumnoOmit<ExtArgs> | null
  /**
   * Filter, which MateriaAlumnos to fetch.
   */
  where?: Prisma.MateriaAlumnoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MateriaAlumnos to fetch.
   */
  orderBy?: Prisma.MateriaAlumnoOrderByWithRelationInput | Prisma.MateriaAlumnoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MateriaAlumnos.
   */
  cursor?: Prisma.MateriaAlumnoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MateriaAlumnos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MateriaAlumnos.
   */
  skip?: number
  distinct?: Prisma.MateriaAlumnoScalarFieldEnum | Prisma.MateriaAlumnoScalarFieldEnum[]
}

/**
 * MateriaAlumno create
 */
export type MateriaAlumnoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MateriaAlumno
   */
  select?: Prisma.MateriaAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MateriaAlumno
   */
  omit?: Prisma.MateriaAlumnoOmit<ExtArgs> | null
  /**
   * The data needed to create a MateriaAlumno.
   */
  data: Prisma.XOR<Prisma.MateriaAlumnoCreateInput, Prisma.MateriaAlumnoUncheckedCreateInput>
}

/**
 * MateriaAlumno createMany
 */
export type MateriaAlumnoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MateriaAlumnos.
   */
  data: Prisma.MateriaAlumnoCreateManyInput | Prisma.MateriaAlumnoCreateManyInput[]
}

/**
 * MateriaAlumno createManyAndReturn
 */
export type MateriaAlumnoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MateriaAlumno
   */
  select?: Prisma.MateriaAlumnoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MateriaAlumno
   */
  omit?: Prisma.MateriaAlumnoOmit<ExtArgs> | null
  /**
   * The data used to create many MateriaAlumnos.
   */
  data: Prisma.MateriaAlumnoCreateManyInput | Prisma.MateriaAlumnoCreateManyInput[]
}

/**
 * MateriaAlumno update
 */
export type MateriaAlumnoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MateriaAlumno
   */
  select?: Prisma.MateriaAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MateriaAlumno
   */
  omit?: Prisma.MateriaAlumnoOmit<ExtArgs> | null
  /**
   * The data needed to update a MateriaAlumno.
   */
  data: Prisma.XOR<Prisma.MateriaAlumnoUpdateInput, Prisma.MateriaAlumnoUncheckedUpdateInput>
  /**
   * Choose, which MateriaAlumno to update.
   */
  where: Prisma.MateriaAlumnoWhereUniqueInput
}

/**
 * MateriaAlumno updateMany
 */
export type MateriaAlumnoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MateriaAlumnos.
   */
  data: Prisma.XOR<Prisma.MateriaAlumnoUpdateManyMutationInput, Prisma.MateriaAlumnoUncheckedUpdateManyInput>
  /**
   * Filter which MateriaAlumnos to update
   */
  where?: Prisma.MateriaAlumnoWhereInput
  /**
   * Limit how many MateriaAlumnos to update.
   */
  limit?: number
}

/**
 * MateriaAlumno updateManyAndReturn
 */
export type MateriaAlumnoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MateriaAlumno
   */
  select?: Prisma.MateriaAlumnoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MateriaAlumno
   */
  omit?: Prisma.MateriaAlumnoOmit<ExtArgs> | null
  /**
   * The data used to update MateriaAlumnos.
   */
  data: Prisma.XOR<Prisma.MateriaAlumnoUpdateManyMutationInput, Prisma.MateriaAlumnoUncheckedUpdateManyInput>
  /**
   * Filter which MateriaAlumnos to update
   */
  where?: Prisma.MateriaAlumnoWhereInput
  /**
   * Limit how many MateriaAlumnos to update.
   */
  limit?: number
}

/**
 * MateriaAlumno upsert
 */
export type MateriaAlumnoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MateriaAlumno
   */
  select?: Prisma.MateriaAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MateriaAlumno
   */
  omit?: Prisma.MateriaAlumnoOmit<ExtArgs> | null
  /**
   * The filter to search for the MateriaAlumno to update in case it exists.
   */
  where: Prisma.MateriaAlumnoWhereUniqueInput
  /**
   * In case the MateriaAlumno found by the `where` argument doesn't exist, create a new MateriaAlumno with this data.
   */
  create: Prisma.XOR<Prisma.MateriaAlumnoCreateInput, Prisma.MateriaAlumnoUncheckedCreateInput>
  /**
   * In case the MateriaAlumno was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MateriaAlumnoUpdateInput, Prisma.MateriaAlumnoUncheckedUpdateInput>
}

/**
 * MateriaAlumno delete
 */
export type MateriaAlumnoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MateriaAlumno
   */
  select?: Prisma.MateriaAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MateriaAlumno
   */
  omit?: Prisma.MateriaAlumnoOmit<ExtArgs> | null
  /**
   * Filter which MateriaAlumno to delete.
   */
  where: Prisma.MateriaAlumnoWhereUniqueInput
}

/**
 * MateriaAlumno deleteMany
 */
export type MateriaAlumnoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MateriaAlumnos to delete
   */
  where?: Prisma.MateriaAlumnoWhereInput
  /**
   * Limit how many MateriaAlumnos to delete.
   */
  limit?: number
}

/**
 * MateriaAlumno without action
 */
export type MateriaAlumnoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MateriaAlumno
   */
  select?: Prisma.MateriaAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MateriaAlumno
   */
  omit?: Prisma.MateriaAlumnoOmit<ExtArgs> | null
}
