
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SesionAlumno` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model SesionAlumno
 * 
 */
export type SesionAlumnoModel = runtime.Types.Result.DefaultSelection<Prisma.$SesionAlumnoPayload>

export type AggregateSesionAlumno = {
  _count: SesionAlumnoCountAggregateOutputType | null
  _min: SesionAlumnoMinAggregateOutputType | null
  _max: SesionAlumnoMaxAggregateOutputType | null
}

export type SesionAlumnoMinAggregateOutputType = {
  id: string | null
  periodoId: string | null
  alumnoId: string | null
  tokenHash: string | null
  expiraEn: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SesionAlumnoMaxAggregateOutputType = {
  id: string | null
  periodoId: string | null
  alumnoId: string | null
  tokenHash: string | null
  expiraEn: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SesionAlumnoCountAggregateOutputType = {
  id: number
  periodoId: number
  alumnoId: number
  tokenHash: number
  expiraEn: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type SesionAlumnoMinAggregateInputType = {
  id?: true
  periodoId?: true
  alumnoId?: true
  tokenHash?: true
  expiraEn?: true
  createdAt?: true
  updatedAt?: true
}

export type SesionAlumnoMaxAggregateInputType = {
  id?: true
  periodoId?: true
  alumnoId?: true
  tokenHash?: true
  expiraEn?: true
  createdAt?: true
  updatedAt?: true
}

export type SesionAlumnoCountAggregateInputType = {
  id?: true
  periodoId?: true
  alumnoId?: true
  tokenHash?: true
  expiraEn?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type SesionAlumnoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SesionAlumno to aggregate.
   */
  where?: Prisma.SesionAlumnoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SesionAlumnos to fetch.
   */
  orderBy?: Prisma.SesionAlumnoOrderByWithRelationInput | Prisma.SesionAlumnoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SesionAlumnoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SesionAlumnos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SesionAlumnos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SesionAlumnos
  **/
  _count?: true | SesionAlumnoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SesionAlumnoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SesionAlumnoMaxAggregateInputType
}

export type GetSesionAlumnoAggregateType<T extends SesionAlumnoAggregateArgs> = {
      [P in keyof T & keyof AggregateSesionAlumno]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSesionAlumno[P]>
    : Prisma.GetScalarType<T[P], AggregateSesionAlumno[P]>
}




export type SesionAlumnoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SesionAlumnoWhereInput
  orderBy?: Prisma.SesionAlumnoOrderByWithAggregationInput | Prisma.SesionAlumnoOrderByWithAggregationInput[]
  by: Prisma.SesionAlumnoScalarFieldEnum[] | Prisma.SesionAlumnoScalarFieldEnum
  having?: Prisma.SesionAlumnoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SesionAlumnoCountAggregateInputType | true
  _min?: SesionAlumnoMinAggregateInputType
  _max?: SesionAlumnoMaxAggregateInputType
}

export type SesionAlumnoGroupByOutputType = {
  id: string
  periodoId: string
  alumnoId: string
  tokenHash: string
  expiraEn: Date
  createdAt: Date
  updatedAt: Date
  _count: SesionAlumnoCountAggregateOutputType | null
  _min: SesionAlumnoMinAggregateOutputType | null
  _max: SesionAlumnoMaxAggregateOutputType | null
}

type GetSesionAlumnoGroupByPayload<T extends SesionAlumnoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SesionAlumnoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SesionAlumnoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SesionAlumnoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SesionAlumnoGroupByOutputType[P]>
      }
    >
  >



export type SesionAlumnoWhereInput = {
  AND?: Prisma.SesionAlumnoWhereInput | Prisma.SesionAlumnoWhereInput[]
  OR?: Prisma.SesionAlumnoWhereInput[]
  NOT?: Prisma.SesionAlumnoWhereInput | Prisma.SesionAlumnoWhereInput[]
  id?: Prisma.StringFilter<"SesionAlumno"> | string
  periodoId?: Prisma.StringFilter<"SesionAlumno"> | string
  alumnoId?: Prisma.StringFilter<"SesionAlumno"> | string
  tokenHash?: Prisma.StringFilter<"SesionAlumno"> | string
  expiraEn?: Prisma.DateTimeFilter<"SesionAlumno"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"SesionAlumno"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SesionAlumno"> | Date | string
}

export type SesionAlumnoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  periodoId?: Prisma.SortOrder
  alumnoId?: Prisma.SortOrder
  tokenHash?: Prisma.SortOrder
  expiraEn?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SesionAlumnoWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  tokenHash?: string
  AND?: Prisma.SesionAlumnoWhereInput | Prisma.SesionAlumnoWhereInput[]
  OR?: Prisma.SesionAlumnoWhereInput[]
  NOT?: Prisma.SesionAlumnoWhereInput | Prisma.SesionAlumnoWhereInput[]
  periodoId?: Prisma.StringFilter<"SesionAlumno"> | string
  alumnoId?: Prisma.StringFilter<"SesionAlumno"> | string
  expiraEn?: Prisma.DateTimeFilter<"SesionAlumno"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"SesionAlumno"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SesionAlumno"> | Date | string
}, "id" | "tokenHash">

export type SesionAlumnoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  periodoId?: Prisma.SortOrder
  alumnoId?: Prisma.SortOrder
  tokenHash?: Prisma.SortOrder
  expiraEn?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.SesionAlumnoCountOrderByAggregateInput
  _max?: Prisma.SesionAlumnoMaxOrderByAggregateInput
  _min?: Prisma.SesionAlumnoMinOrderByAggregateInput
}

export type SesionAlumnoScalarWhereWithAggregatesInput = {
  AND?: Prisma.SesionAlumnoScalarWhereWithAggregatesInput | Prisma.SesionAlumnoScalarWhereWithAggregatesInput[]
  OR?: Prisma.SesionAlumnoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SesionAlumnoScalarWhereWithAggregatesInput | Prisma.SesionAlumnoScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SesionAlumno"> | string
  periodoId?: Prisma.StringWithAggregatesFilter<"SesionAlumno"> | string
  alumnoId?: Prisma.StringWithAggregatesFilter<"SesionAlumno"> | string
  tokenHash?: Prisma.StringWithAggregatesFilter<"SesionAlumno"> | string
  expiraEn?: Prisma.DateTimeWithAggregatesFilter<"SesionAlumno"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SesionAlumno"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"SesionAlumno"> | Date | string
}

export type SesionAlumnoCreateInput = {
  id?: string
  periodoId: string
  alumnoId: string
  tokenHash: string
  expiraEn: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SesionAlumnoUncheckedCreateInput = {
  id?: string
  periodoId: string
  alumnoId: string
  tokenHash: string
  expiraEn: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SesionAlumnoUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  periodoId?: Prisma.StringFieldUpdateOperationsInput | string
  alumnoId?: Prisma.StringFieldUpdateOperationsInput | string
  tokenHash?: Prisma.StringFieldUpdateOperationsInput | string
  expiraEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SesionAlumnoUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  periodoId?: Prisma.StringFieldUpdateOperationsInput | string
  alumnoId?: Prisma.StringFieldUpdateOperationsInput | string
  tokenHash?: Prisma.StringFieldUpdateOperationsInput | string
  expiraEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SesionAlumnoCreateManyInput = {
  id?: string
  periodoId: string
  alumnoId: string
  tokenHash: string
  expiraEn: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SesionAlumnoUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  periodoId?: Prisma.StringFieldUpdateOperationsInput | string
  alumnoId?: Prisma.StringFieldUpdateOperationsInput | string
  tokenHash?: Prisma.StringFieldUpdateOperationsInput | string
  expiraEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SesionAlumnoUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  periodoId?: Prisma.StringFieldUpdateOperationsInput | string
  alumnoId?: Prisma.StringFieldUpdateOperationsInput | string
  tokenHash?: Prisma.StringFieldUpdateOperationsInput | string
  expiraEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SesionAlumnoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  periodoId?: Prisma.SortOrder
  alumnoId?: Prisma.SortOrder
  tokenHash?: Prisma.SortOrder
  expiraEn?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SesionAlumnoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  periodoId?: Prisma.SortOrder
  alumnoId?: Prisma.SortOrder
  tokenHash?: Prisma.SortOrder
  expiraEn?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SesionAlumnoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  periodoId?: Prisma.SortOrder
  alumnoId?: Prisma.SortOrder
  tokenHash?: Prisma.SortOrder
  expiraEn?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}



export type SesionAlumnoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  periodoId?: boolean
  alumnoId?: boolean
  tokenHash?: boolean
  expiraEn?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["sesionAlumno"]>

export type SesionAlumnoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  periodoId?: boolean
  alumnoId?: boolean
  tokenHash?: boolean
  expiraEn?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["sesionAlumno"]>

export type SesionAlumnoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  periodoId?: boolean
  alumnoId?: boolean
  tokenHash?: boolean
  expiraEn?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["sesionAlumno"]>

export type SesionAlumnoSelectScalar = {
  id?: boolean
  periodoId?: boolean
  alumnoId?: boolean
  tokenHash?: boolean
  expiraEn?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type SesionAlumnoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "periodoId" | "alumnoId" | "tokenHash" | "expiraEn" | "createdAt" | "updatedAt", ExtArgs["result"]["sesionAlumno"]>

export type $SesionAlumnoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SesionAlumno"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    periodoId: string
    alumnoId: string
    tokenHash: string
    expiraEn: Date
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["sesionAlumno"]>
  composites: {}
}

export type SesionAlumnoGetPayload<S extends boolean | null | undefined | SesionAlumnoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SesionAlumnoPayload, S>

export type SesionAlumnoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SesionAlumnoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SesionAlumnoCountAggregateInputType | true
  }

export interface SesionAlumnoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SesionAlumno'], meta: { name: 'SesionAlumno' } }
  /**
   * Find zero or one SesionAlumno that matches the filter.
   * @param {SesionAlumnoFindUniqueArgs} args - Arguments to find a SesionAlumno
   * @example
   * // Get one SesionAlumno
   * const sesionAlumno = await prisma.sesionAlumno.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SesionAlumnoFindUniqueArgs>(args: Prisma.SelectSubset<T, SesionAlumnoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SesionAlumnoClient<runtime.Types.Result.GetResult<Prisma.$SesionAlumnoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SesionAlumno that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SesionAlumnoFindUniqueOrThrowArgs} args - Arguments to find a SesionAlumno
   * @example
   * // Get one SesionAlumno
   * const sesionAlumno = await prisma.sesionAlumno.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SesionAlumnoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SesionAlumnoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SesionAlumnoClient<runtime.Types.Result.GetResult<Prisma.$SesionAlumnoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SesionAlumno that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SesionAlumnoFindFirstArgs} args - Arguments to find a SesionAlumno
   * @example
   * // Get one SesionAlumno
   * const sesionAlumno = await prisma.sesionAlumno.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SesionAlumnoFindFirstArgs>(args?: Prisma.SelectSubset<T, SesionAlumnoFindFirstArgs<ExtArgs>>): Prisma.Prisma__SesionAlumnoClient<runtime.Types.Result.GetResult<Prisma.$SesionAlumnoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SesionAlumno that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SesionAlumnoFindFirstOrThrowArgs} args - Arguments to find a SesionAlumno
   * @example
   * // Get one SesionAlumno
   * const sesionAlumno = await prisma.sesionAlumno.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SesionAlumnoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SesionAlumnoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SesionAlumnoClient<runtime.Types.Result.GetResult<Prisma.$SesionAlumnoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SesionAlumnos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SesionAlumnoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SesionAlumnos
   * const sesionAlumnos = await prisma.sesionAlumno.findMany()
   * 
   * // Get first 10 SesionAlumnos
   * const sesionAlumnos = await prisma.sesionAlumno.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sesionAlumnoWithIdOnly = await prisma.sesionAlumno.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SesionAlumnoFindManyArgs>(args?: Prisma.SelectSubset<T, SesionAlumnoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SesionAlumnoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SesionAlumno.
   * @param {SesionAlumnoCreateArgs} args - Arguments to create a SesionAlumno.
   * @example
   * // Create one SesionAlumno
   * const SesionAlumno = await prisma.sesionAlumno.create({
   *   data: {
   *     // ... data to create a SesionAlumno
   *   }
   * })
   * 
   */
  create<T extends SesionAlumnoCreateArgs>(args: Prisma.SelectSubset<T, SesionAlumnoCreateArgs<ExtArgs>>): Prisma.Prisma__SesionAlumnoClient<runtime.Types.Result.GetResult<Prisma.$SesionAlumnoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SesionAlumnos.
   * @param {SesionAlumnoCreateManyArgs} args - Arguments to create many SesionAlumnos.
   * @example
   * // Create many SesionAlumnos
   * const sesionAlumno = await prisma.sesionAlumno.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SesionAlumnoCreateManyArgs>(args?: Prisma.SelectSubset<T, SesionAlumnoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SesionAlumnos and returns the data saved in the database.
   * @param {SesionAlumnoCreateManyAndReturnArgs} args - Arguments to create many SesionAlumnos.
   * @example
   * // Create many SesionAlumnos
   * const sesionAlumno = await prisma.sesionAlumno.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SesionAlumnos and only return the `id`
   * const sesionAlumnoWithIdOnly = await prisma.sesionAlumno.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SesionAlumnoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SesionAlumnoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SesionAlumnoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SesionAlumno.
   * @param {SesionAlumnoDeleteArgs} args - Arguments to delete one SesionAlumno.
   * @example
   * // Delete one SesionAlumno
   * const SesionAlumno = await prisma.sesionAlumno.delete({
   *   where: {
   *     // ... filter to delete one SesionAlumno
   *   }
   * })
   * 
   */
  delete<T extends SesionAlumnoDeleteArgs>(args: Prisma.SelectSubset<T, SesionAlumnoDeleteArgs<ExtArgs>>): Prisma.Prisma__SesionAlumnoClient<runtime.Types.Result.GetResult<Prisma.$SesionAlumnoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SesionAlumno.
   * @param {SesionAlumnoUpdateArgs} args - Arguments to update one SesionAlumno.
   * @example
   * // Update one SesionAlumno
   * const sesionAlumno = await prisma.sesionAlumno.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SesionAlumnoUpdateArgs>(args: Prisma.SelectSubset<T, SesionAlumnoUpdateArgs<ExtArgs>>): Prisma.Prisma__SesionAlumnoClient<runtime.Types.Result.GetResult<Prisma.$SesionAlumnoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SesionAlumnos.
   * @param {SesionAlumnoDeleteManyArgs} args - Arguments to filter SesionAlumnos to delete.
   * @example
   * // Delete a few SesionAlumnos
   * const { count } = await prisma.sesionAlumno.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SesionAlumnoDeleteManyArgs>(args?: Prisma.SelectSubset<T, SesionAlumnoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SesionAlumnos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SesionAlumnoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SesionAlumnos
   * const sesionAlumno = await prisma.sesionAlumno.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SesionAlumnoUpdateManyArgs>(args: Prisma.SelectSubset<T, SesionAlumnoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SesionAlumnos and returns the data updated in the database.
   * @param {SesionAlumnoUpdateManyAndReturnArgs} args - Arguments to update many SesionAlumnos.
   * @example
   * // Update many SesionAlumnos
   * const sesionAlumno = await prisma.sesionAlumno.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SesionAlumnos and only return the `id`
   * const sesionAlumnoWithIdOnly = await prisma.sesionAlumno.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SesionAlumnoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SesionAlumnoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SesionAlumnoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SesionAlumno.
   * @param {SesionAlumnoUpsertArgs} args - Arguments to update or create a SesionAlumno.
   * @example
   * // Update or create a SesionAlumno
   * const sesionAlumno = await prisma.sesionAlumno.upsert({
   *   create: {
   *     // ... data to create a SesionAlumno
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SesionAlumno we want to update
   *   }
   * })
   */
  upsert<T extends SesionAlumnoUpsertArgs>(args: Prisma.SelectSubset<T, SesionAlumnoUpsertArgs<ExtArgs>>): Prisma.Prisma__SesionAlumnoClient<runtime.Types.Result.GetResult<Prisma.$SesionAlumnoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SesionAlumnos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SesionAlumnoCountArgs} args - Arguments to filter SesionAlumnos to count.
   * @example
   * // Count the number of SesionAlumnos
   * const count = await prisma.sesionAlumno.count({
   *   where: {
   *     // ... the filter for the SesionAlumnos we want to count
   *   }
   * })
  **/
  count<T extends SesionAlumnoCountArgs>(
    args?: Prisma.Subset<T, SesionAlumnoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SesionAlumnoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SesionAlumno.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SesionAlumnoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SesionAlumnoAggregateArgs>(args: Prisma.Subset<T, SesionAlumnoAggregateArgs>): Prisma.PrismaPromise<GetSesionAlumnoAggregateType<T>>

  /**
   * Group by SesionAlumno.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SesionAlumnoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SesionAlumnoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SesionAlumnoGroupByArgs['orderBy'] }
      : { orderBy?: SesionAlumnoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SesionAlumnoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSesionAlumnoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SesionAlumno model
 */
readonly fields: SesionAlumnoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SesionAlumno.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SesionAlumnoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SesionAlumno model
 */
export interface SesionAlumnoFieldRefs {
  readonly id: Prisma.FieldRef<"SesionAlumno", 'String'>
  readonly periodoId: Prisma.FieldRef<"SesionAlumno", 'String'>
  readonly alumnoId: Prisma.FieldRef<"SesionAlumno", 'String'>
  readonly tokenHash: Prisma.FieldRef<"SesionAlumno", 'String'>
  readonly expiraEn: Prisma.FieldRef<"SesionAlumno", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"SesionAlumno", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"SesionAlumno", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SesionAlumno findUnique
 */
export type SesionAlumnoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesionAlumno
   */
  select?: Prisma.SesionAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SesionAlumno
   */
  omit?: Prisma.SesionAlumnoOmit<ExtArgs> | null
  /**
   * Filter, which SesionAlumno to fetch.
   */
  where: Prisma.SesionAlumnoWhereUniqueInput
}

/**
 * SesionAlumno findUniqueOrThrow
 */
export type SesionAlumnoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesionAlumno
   */
  select?: Prisma.SesionAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SesionAlumno
   */
  omit?: Prisma.SesionAlumnoOmit<ExtArgs> | null
  /**
   * Filter, which SesionAlumno to fetch.
   */
  where: Prisma.SesionAlumnoWhereUniqueInput
}

/**
 * SesionAlumno findFirst
 */
export type SesionAlumnoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesionAlumno
   */
  select?: Prisma.SesionAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SesionAlumno
   */
  omit?: Prisma.SesionAlumnoOmit<ExtArgs> | null
  /**
   * Filter, which SesionAlumno to fetch.
   */
  where?: Prisma.SesionAlumnoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SesionAlumnos to fetch.
   */
  orderBy?: Prisma.SesionAlumnoOrderByWithRelationInput | Prisma.SesionAlumnoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SesionAlumnos.
   */
  cursor?: Prisma.SesionAlumnoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SesionAlumnos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SesionAlumnos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SesionAlumnos.
   */
  distinct?: Prisma.SesionAlumnoScalarFieldEnum | Prisma.SesionAlumnoScalarFieldEnum[]
}

/**
 * SesionAlumno findFirstOrThrow
 */
export type SesionAlumnoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesionAlumno
   */
  select?: Prisma.SesionAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SesionAlumno
   */
  omit?: Prisma.SesionAlumnoOmit<ExtArgs> | null
  /**
   * Filter, which SesionAlumno to fetch.
   */
  where?: Prisma.SesionAlumnoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SesionAlumnos to fetch.
   */
  orderBy?: Prisma.SesionAlumnoOrderByWithRelationInput | Prisma.SesionAlumnoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SesionAlumnos.
   */
  cursor?: Prisma.SesionAlumnoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SesionAlumnos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SesionAlumnos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SesionAlumnos.
   */
  distinct?: Prisma.SesionAlumnoScalarFieldEnum | Prisma.SesionAlumnoScalarFieldEnum[]
}

/**
 * SesionAlumno findMany
 */
export type SesionAlumnoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesionAlumno
   */
  select?: Prisma.SesionAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SesionAlumno
   */
  omit?: Prisma.SesionAlumnoOmit<ExtArgs> | null
  /**
   * Filter, which SesionAlumnos to fetch.
   */
  where?: Prisma.SesionAlumnoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SesionAlumnos to fetch.
   */
  orderBy?: Prisma.SesionAlumnoOrderByWithRelationInput | Prisma.SesionAlumnoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SesionAlumnos.
   */
  cursor?: Prisma.SesionAlumnoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SesionAlumnos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SesionAlumnos.
   */
  skip?: number
  distinct?: Prisma.SesionAlumnoScalarFieldEnum | Prisma.SesionAlumnoScalarFieldEnum[]
}

/**
 * SesionAlumno create
 */
export type SesionAlumnoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesionAlumno
   */
  select?: Prisma.SesionAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SesionAlumno
   */
  omit?: Prisma.SesionAlumnoOmit<ExtArgs> | null
  /**
   * The data needed to create a SesionAlumno.
   */
  data: Prisma.XOR<Prisma.SesionAlumnoCreateInput, Prisma.SesionAlumnoUncheckedCreateInput>
}

/**
 * SesionAlumno createMany
 */
export type SesionAlumnoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SesionAlumnos.
   */
  data: Prisma.SesionAlumnoCreateManyInput | Prisma.SesionAlumnoCreateManyInput[]
}

/**
 * SesionAlumno createManyAndReturn
 */
export type SesionAlumnoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesionAlumno
   */
  select?: Prisma.SesionAlumnoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SesionAlumno
   */
  omit?: Prisma.SesionAlumnoOmit<ExtArgs> | null
  /**
   * The data used to create many SesionAlumnos.
   */
  data: Prisma.SesionAlumnoCreateManyInput | Prisma.SesionAlumnoCreateManyInput[]
}

/**
 * SesionAlumno update
 */
export type SesionAlumnoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesionAlumno
   */
  select?: Prisma.SesionAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SesionAlumno
   */
  omit?: Prisma.SesionAlumnoOmit<ExtArgs> | null
  /**
   * The data needed to update a SesionAlumno.
   */
  data: Prisma.XOR<Prisma.SesionAlumnoUpdateInput, Prisma.SesionAlumnoUncheckedUpdateInput>
  /**
   * Choose, which SesionAlumno to update.
   */
  where: Prisma.SesionAlumnoWhereUniqueInput
}

/**
 * SesionAlumno updateMany
 */
export type SesionAlumnoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SesionAlumnos.
   */
  data: Prisma.XOR<Prisma.SesionAlumnoUpdateManyMutationInput, Prisma.SesionAlumnoUncheckedUpdateManyInput>
  /**
   * Filter which SesionAlumnos to update
   */
  where?: Prisma.SesionAlumnoWhereInput
  /**
   * Limit how many SesionAlumnos to update.
   */
  limit?: number
}

/**
 * SesionAlumno updateManyAndReturn
 */
export type SesionAlumnoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesionAlumno
   */
  select?: Prisma.SesionAlumnoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SesionAlumno
   */
  omit?: Prisma.SesionAlumnoOmit<ExtArgs> | null
  /**
   * The data used to update SesionAlumnos.
   */
  data: Prisma.XOR<Prisma.SesionAlumnoUpdateManyMutationInput, Prisma.SesionAlumnoUncheckedUpdateManyInput>
  /**
   * Filter which SesionAlumnos to update
   */
  where?: Prisma.SesionAlumnoWhereInput
  /**
   * Limit how many SesionAlumnos to update.
   */
  limit?: number
}

/**
 * SesionAlumno upsert
 */
export type SesionAlumnoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesionAlumno
   */
  select?: Prisma.SesionAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SesionAlumno
   */
  omit?: Prisma.SesionAlumnoOmit<ExtArgs> | null
  /**
   * The filter to search for the SesionAlumno to update in case it exists.
   */
  where: Prisma.SesionAlumnoWhereUniqueInput
  /**
   * In case the SesionAlumno found by the `where` argument doesn't exist, create a new SesionAlumno with this data.
   */
  create: Prisma.XOR<Prisma.SesionAlumnoCreateInput, Prisma.SesionAlumnoUncheckedCreateInput>
  /**
   * In case the SesionAlumno was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SesionAlumnoUpdateInput, Prisma.SesionAlumnoUncheckedUpdateInput>
}

/**
 * SesionAlumno delete
 */
export type SesionAlumnoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesionAlumno
   */
  select?: Prisma.SesionAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SesionAlumno
   */
  omit?: Prisma.SesionAlumnoOmit<ExtArgs> | null
  /**
   * Filter which SesionAlumno to delete.
   */
  where: Prisma.SesionAlumnoWhereUniqueInput
}

/**
 * SesionAlumno deleteMany
 */
export type SesionAlumnoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SesionAlumnos to delete
   */
  where?: Prisma.SesionAlumnoWhereInput
  /**
   * Limit how many SesionAlumnos to delete.
   */
  limit?: number
}

/**
 * SesionAlumno without action
 */
export type SesionAlumnoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SesionAlumno
   */
  select?: Prisma.SesionAlumnoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SesionAlumno
   */
  omit?: Prisma.SesionAlumnoOmit<ExtArgs> | null
}
