
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SolicitudRevision` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model SolicitudRevision
 * 
 */
export type SolicitudRevisionModel = runtime.Types.Result.DefaultSelection<Prisma.$SolicitudRevisionPayload>

export type AggregateSolicitudRevision = {
  _count: SolicitudRevisionCountAggregateOutputType | null
  _avg: SolicitudRevisionAvgAggregateOutputType | null
  _sum: SolicitudRevisionSumAggregateOutputType | null
  _min: SolicitudRevisionMinAggregateOutputType | null
  _max: SolicitudRevisionMaxAggregateOutputType | null
}

export type SolicitudRevisionAvgAggregateOutputType = {
  numeroPregunta: number | null
}

export type SolicitudRevisionSumAggregateOutputType = {
  numeroPregunta: number | null
}

export type SolicitudRevisionMinAggregateOutputType = {
  id: string | null
  externoId: string | null
  periodoId: string | null
  docenteId: string | null
  alumnoId: string | null
  examenGeneradoId: string | null
  folio: string | null
  numeroPregunta: number | null
  comentario: string | null
  estado: string | null
  solicitadoEn: Date | null
  atendidoEn: Date | null
  respuestaDocente: string | null
  firmaDocente: string | null
  firmadoEn: Date | null
  cerradoEn: Date | null
  conformidadAlumno: boolean | null
  conformidadActualizadaEn: Date | null
  origen: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SolicitudRevisionMaxAggregateOutputType = {
  id: string | null
  externoId: string | null
  periodoId: string | null
  docenteId: string | null
  alumnoId: string | null
  examenGeneradoId: string | null
  folio: string | null
  numeroPregunta: number | null
  comentario: string | null
  estado: string | null
  solicitadoEn: Date | null
  atendidoEn: Date | null
  respuestaDocente: string | null
  firmaDocente: string | null
  firmadoEn: Date | null
  cerradoEn: Date | null
  conformidadAlumno: boolean | null
  conformidadActualizadaEn: Date | null
  origen: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SolicitudRevisionCountAggregateOutputType = {
  id: number
  externoId: number
  periodoId: number
  docenteId: number
  alumnoId: number
  examenGeneradoId: number
  folio: number
  numeroPregunta: number
  comentario: number
  estado: number
  solicitadoEn: number
  atendidoEn: number
  respuestaDocente: number
  firmaDocente: number
  firmadoEn: number
  cerradoEn: number
  conformidadAlumno: number
  conformidadActualizadaEn: number
  origen: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type SolicitudRevisionAvgAggregateInputType = {
  numeroPregunta?: true
}

export type SolicitudRevisionSumAggregateInputType = {
  numeroPregunta?: true
}

export type SolicitudRevisionMinAggregateInputType = {
  id?: true
  externoId?: true
  periodoId?: true
  docenteId?: true
  alumnoId?: true
  examenGeneradoId?: true
  folio?: true
  numeroPregunta?: true
  comentario?: true
  estado?: true
  solicitadoEn?: true
  atendidoEn?: true
  respuestaDocente?: true
  firmaDocente?: true
  firmadoEn?: true
  cerradoEn?: true
  conformidadAlumno?: true
  conformidadActualizadaEn?: true
  origen?: true
  createdAt?: true
  updatedAt?: true
}

export type SolicitudRevisionMaxAggregateInputType = {
  id?: true
  externoId?: true
  periodoId?: true
  docenteId?: true
  alumnoId?: true
  examenGeneradoId?: true
  folio?: true
  numeroPregunta?: true
  comentario?: true
  estado?: true
  solicitadoEn?: true
  atendidoEn?: true
  respuestaDocente?: true
  firmaDocente?: true
  firmadoEn?: true
  cerradoEn?: true
  conformidadAlumno?: true
  conformidadActualizadaEn?: true
  origen?: true
  createdAt?: true
  updatedAt?: true
}

export type SolicitudRevisionCountAggregateInputType = {
  id?: true
  externoId?: true
  periodoId?: true
  docenteId?: true
  alumnoId?: true
  examenGeneradoId?: true
  folio?: true
  numeroPregunta?: true
  comentario?: true
  estado?: true
  solicitadoEn?: true
  atendidoEn?: true
  respuestaDocente?: true
  firmaDocente?: true
  firmadoEn?: true
  cerradoEn?: true
  conformidadAlumno?: true
  conformidadActualizadaEn?: true
  origen?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type SolicitudRevisionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SolicitudRevision to aggregate.
   */
  where?: Prisma.SolicitudRevisionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SolicitudRevisions to fetch.
   */
  orderBy?: Prisma.SolicitudRevisionOrderByWithRelationInput | Prisma.SolicitudRevisionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SolicitudRevisionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SolicitudRevisions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SolicitudRevisions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SolicitudRevisions
  **/
  _count?: true | SolicitudRevisionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SolicitudRevisionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SolicitudRevisionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SolicitudRevisionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SolicitudRevisionMaxAggregateInputType
}

export type GetSolicitudRevisionAggregateType<T extends SolicitudRevisionAggregateArgs> = {
      [P in keyof T & keyof AggregateSolicitudRevision]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSolicitudRevision[P]>
    : Prisma.GetScalarType<T[P], AggregateSolicitudRevision[P]>
}




export type SolicitudRevisionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SolicitudRevisionWhereInput
  orderBy?: Prisma.SolicitudRevisionOrderByWithAggregationInput | Prisma.SolicitudRevisionOrderByWithAggregationInput[]
  by: Prisma.SolicitudRevisionScalarFieldEnum[] | Prisma.SolicitudRevisionScalarFieldEnum
  having?: Prisma.SolicitudRevisionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SolicitudRevisionCountAggregateInputType | true
  _avg?: SolicitudRevisionAvgAggregateInputType
  _sum?: SolicitudRevisionSumAggregateInputType
  _min?: SolicitudRevisionMinAggregateInputType
  _max?: SolicitudRevisionMaxAggregateInputType
}

export type SolicitudRevisionGroupByOutputType = {
  id: string
  externoId: string
  periodoId: string
  docenteId: string
  alumnoId: string
  examenGeneradoId: string | null
  folio: string
  numeroPregunta: number
  comentario: string | null
  estado: string
  solicitadoEn: Date
  atendidoEn: Date | null
  respuestaDocente: string | null
  firmaDocente: string | null
  firmadoEn: Date | null
  cerradoEn: Date | null
  conformidadAlumno: boolean
  conformidadActualizadaEn: Date | null
  origen: string
  createdAt: Date
  updatedAt: Date
  _count: SolicitudRevisionCountAggregateOutputType | null
  _avg: SolicitudRevisionAvgAggregateOutputType | null
  _sum: SolicitudRevisionSumAggregateOutputType | null
  _min: SolicitudRevisionMinAggregateOutputType | null
  _max: SolicitudRevisionMaxAggregateOutputType | null
}

type GetSolicitudRevisionGroupByPayload<T extends SolicitudRevisionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SolicitudRevisionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SolicitudRevisionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SolicitudRevisionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SolicitudRevisionGroupByOutputType[P]>
      }
    >
  >



export type SolicitudRevisionWhereInput = {
  AND?: Prisma.SolicitudRevisionWhereInput | Prisma.SolicitudRevisionWhereInput[]
  OR?: Prisma.SolicitudRevisionWhereInput[]
  NOT?: Prisma.SolicitudRevisionWhereInput | Prisma.SolicitudRevisionWhereInput[]
  id?: Prisma.StringFilter<"SolicitudRevision"> | string
  externoId?: Prisma.StringFilter<"SolicitudRevision"> | string
  periodoId?: Prisma.StringFilter<"SolicitudRevision"> | string
  docenteId?: Prisma.StringFilter<"SolicitudRevision"> | string
  alumnoId?: Prisma.StringFilter<"SolicitudRevision"> | string
  examenGeneradoId?: Prisma.StringNullableFilter<"SolicitudRevision"> | string | null
  folio?: Prisma.StringFilter<"SolicitudRevision"> | string
  numeroPregunta?: Prisma.IntFilter<"SolicitudRevision"> | number
  comentario?: Prisma.StringNullableFilter<"SolicitudRevision"> | string | null
  estado?: Prisma.StringFilter<"SolicitudRevision"> | string
  solicitadoEn?: Prisma.DateTimeFilter<"SolicitudRevision"> | Date | string
  atendidoEn?: Prisma.DateTimeNullableFilter<"SolicitudRevision"> | Date | string | null
  respuestaDocente?: Prisma.StringNullableFilter<"SolicitudRevision"> | string | null
  firmaDocente?: Prisma.StringNullableFilter<"SolicitudRevision"> | string | null
  firmadoEn?: Prisma.DateTimeNullableFilter<"SolicitudRevision"> | Date | string | null
  cerradoEn?: Prisma.DateTimeNullableFilter<"SolicitudRevision"> | Date | string | null
  conformidadAlumno?: Prisma.BoolFilter<"SolicitudRevision"> | boolean
  conformidadActualizadaEn?: Prisma.DateTimeNullableFilter<"SolicitudRevision"> | Date | string | null
  origen?: Prisma.StringFilter<"SolicitudRevision"> | string
  createdAt?: Prisma.DateTimeFilter<"SolicitudRevision"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SolicitudRevision"> | Date | string
}

export type SolicitudRevisionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  externoId?: Prisma.SortOrder
  periodoId?: Prisma.SortOrder
  docenteId?: Prisma.SortOrder
  alumnoId?: Prisma.SortOrder
  examenGeneradoId?: Prisma.SortOrderInput | Prisma.SortOrder
  folio?: Prisma.SortOrder
  numeroPregunta?: Prisma.SortOrder
  comentario?: Prisma.SortOrderInput | Prisma.SortOrder
  estado?: Prisma.SortOrder
  solicitadoEn?: Prisma.SortOrder
  atendidoEn?: Prisma.SortOrderInput | Prisma.SortOrder
  respuestaDocente?: Prisma.SortOrderInput | Prisma.SortOrder
  firmaDocente?: Prisma.SortOrderInput | Prisma.SortOrder
  firmadoEn?: Prisma.SortOrderInput | Prisma.SortOrder
  cerradoEn?: Prisma.SortOrderInput | Prisma.SortOrder
  conformidadAlumno?: Prisma.SortOrder
  conformidadActualizadaEn?: Prisma.SortOrderInput | Prisma.SortOrder
  origen?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SolicitudRevisionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  externoId?: string
  AND?: Prisma.SolicitudRevisionWhereInput | Prisma.SolicitudRevisionWhereInput[]
  OR?: Prisma.SolicitudRevisionWhereInput[]
  NOT?: Prisma.SolicitudRevisionWhereInput | Prisma.SolicitudRevisionWhereInput[]
  periodoId?: Prisma.StringFilter<"SolicitudRevision"> | string
  docenteId?: Prisma.StringFilter<"SolicitudRevision"> | string
  alumnoId?: Prisma.StringFilter<"SolicitudRevision"> | string
  examenGeneradoId?: Prisma.StringNullableFilter<"SolicitudRevision"> | string | null
  folio?: Prisma.StringFilter<"SolicitudRevision"> | string
  numeroPregunta?: Prisma.IntFilter<"SolicitudRevision"> | number
  comentario?: Prisma.StringNullableFilter<"SolicitudRevision"> | string | null
  estado?: Prisma.StringFilter<"SolicitudRevision"> | string
  solicitadoEn?: Prisma.DateTimeFilter<"SolicitudRevision"> | Date | string
  atendidoEn?: Prisma.DateTimeNullableFilter<"SolicitudRevision"> | Date | string | null
  respuestaDocente?: Prisma.StringNullableFilter<"SolicitudRevision"> | string | null
  firmaDocente?: Prisma.StringNullableFilter<"SolicitudRevision"> | string | null
  firmadoEn?: Prisma.DateTimeNullableFilter<"SolicitudRevision"> | Date | string | null
  cerradoEn?: Prisma.DateTimeNullableFilter<"SolicitudRevision"> | Date | string | null
  conformidadAlumno?: Prisma.BoolFilter<"SolicitudRevision"> | boolean
  conformidadActualizadaEn?: Prisma.DateTimeNullableFilter<"SolicitudRevision"> | Date | string | null
  origen?: Prisma.StringFilter<"SolicitudRevision"> | string
  createdAt?: Prisma.DateTimeFilter<"SolicitudRevision"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SolicitudRevision"> | Date | string
}, "id" | "externoId">

export type SolicitudRevisionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  externoId?: Prisma.SortOrder
  periodoId?: Prisma.SortOrder
  docenteId?: Prisma.SortOrder
  alumnoId?: Prisma.SortOrder
  examenGeneradoId?: Prisma.SortOrderInput | Prisma.SortOrder
  folio?: Prisma.SortOrder
  numeroPregunta?: Prisma.SortOrder
  comentario?: Prisma.SortOrderInput | Prisma.SortOrder
  estado?: Prisma.SortOrder
  solicitadoEn?: Prisma.SortOrder
  atendidoEn?: Prisma.SortOrderInput | Prisma.SortOrder
  respuestaDocente?: Prisma.SortOrderInput | Prisma.SortOrder
  firmaDocente?: Prisma.SortOrderInput | Prisma.SortOrder
  firmadoEn?: Prisma.SortOrderInput | Prisma.SortOrder
  cerradoEn?: Prisma.SortOrderInput | Prisma.SortOrder
  conformidadAlumno?: Prisma.SortOrder
  conformidadActualizadaEn?: Prisma.SortOrderInput | Prisma.SortOrder
  origen?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.SolicitudRevisionCountOrderByAggregateInput
  _avg?: Prisma.SolicitudRevisionAvgOrderByAggregateInput
  _max?: Prisma.SolicitudRevisionMaxOrderByAggregateInput
  _min?: Prisma.SolicitudRevisionMinOrderByAggregateInput
  _sum?: Prisma.SolicitudRevisionSumOrderByAggregateInput
}

export type SolicitudRevisionScalarWhereWithAggregatesInput = {
  AND?: Prisma.SolicitudRevisionScalarWhereWithAggregatesInput | Prisma.SolicitudRevisionScalarWhereWithAggregatesInput[]
  OR?: Prisma.SolicitudRevisionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SolicitudRevisionScalarWhereWithAggregatesInput | Prisma.SolicitudRevisionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SolicitudRevision"> | string
  externoId?: Prisma.StringWithAggregatesFilter<"SolicitudRevision"> | string
  periodoId?: Prisma.StringWithAggregatesFilter<"SolicitudRevision"> | string
  docenteId?: Prisma.StringWithAggregatesFilter<"SolicitudRevision"> | string
  alumnoId?: Prisma.StringWithAggregatesFilter<"SolicitudRevision"> | string
  examenGeneradoId?: Prisma.StringNullableWithAggregatesFilter<"SolicitudRevision"> | string | null
  folio?: Prisma.StringWithAggregatesFilter<"SolicitudRevision"> | string
  numeroPregunta?: Prisma.IntWithAggregatesFilter<"SolicitudRevision"> | number
  comentario?: Prisma.StringNullableWithAggregatesFilter<"SolicitudRevision"> | string | null
  estado?: Prisma.StringWithAggregatesFilter<"SolicitudRevision"> | string
  solicitadoEn?: Prisma.DateTimeWithAggregatesFilter<"SolicitudRevision"> | Date | string
  atendidoEn?: Prisma.DateTimeNullableWithAggregatesFilter<"SolicitudRevision"> | Date | string | null
  respuestaDocente?: Prisma.StringNullableWithAggregatesFilter<"SolicitudRevision"> | string | null
  firmaDocente?: Prisma.StringNullableWithAggregatesFilter<"SolicitudRevision"> | string | null
  firmadoEn?: Prisma.DateTimeNullableWithAggregatesFilter<"SolicitudRevision"> | Date | string | null
  cerradoEn?: Prisma.DateTimeNullableWithAggregatesFilter<"SolicitudRevision"> | Date | string | null
  conformidadAlumno?: Prisma.BoolWithAggregatesFilter<"SolicitudRevision"> | boolean
  conformidadActualizadaEn?: Prisma.DateTimeNullableWithAggregatesFilter<"SolicitudRevision"> | Date | string | null
  origen?: Prisma.StringWithAggregatesFilter<"SolicitudRevision"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SolicitudRevision"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"SolicitudRevision"> | Date | string
}

export type SolicitudRevisionCreateInput = {
  id?: string
  externoId: string
  periodoId: string
  docenteId: string
  alumnoId: string
  examenGeneradoId?: string | null
  folio: string
  numeroPregunta: number
  comentario?: string | null
  estado?: string
  solicitadoEn: Date | string
  atendidoEn?: Date | string | null
  respuestaDocente?: string | null
  firmaDocente?: string | null
  firmadoEn?: Date | string | null
  cerradoEn?: Date | string | null
  conformidadAlumno?: boolean
  conformidadActualizadaEn?: Date | string | null
  origen?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SolicitudRevisionUncheckedCreateInput = {
  id?: string
  externoId: string
  periodoId: string
  docenteId: string
  alumnoId: string
  examenGeneradoId?: string | null
  folio: string
  numeroPregunta: number
  comentario?: string | null
  estado?: string
  solicitadoEn: Date | string
  atendidoEn?: Date | string | null
  respuestaDocente?: string | null
  firmaDocente?: string | null
  firmadoEn?: Date | string | null
  cerradoEn?: Date | string | null
  conformidadAlumno?: boolean
  conformidadActualizadaEn?: Date | string | null
  origen?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SolicitudRevisionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  externoId?: Prisma.StringFieldUpdateOperationsInput | string
  periodoId?: Prisma.StringFieldUpdateOperationsInput | string
  docenteId?: Prisma.StringFieldUpdateOperationsInput | string
  alumnoId?: Prisma.StringFieldUpdateOperationsInput | string
  examenGeneradoId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  folio?: Prisma.StringFieldUpdateOperationsInput | string
  numeroPregunta?: Prisma.IntFieldUpdateOperationsInput | number
  comentario?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  solicitadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  atendidoEn?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  respuestaDocente?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  firmaDocente?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  firmadoEn?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  cerradoEn?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  conformidadAlumno?: Prisma.BoolFieldUpdateOperationsInput | boolean
  conformidadActualizadaEn?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  origen?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SolicitudRevisionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  externoId?: Prisma.StringFieldUpdateOperationsInput | string
  periodoId?: Prisma.StringFieldUpdateOperationsInput | string
  docenteId?: Prisma.StringFieldUpdateOperationsInput | string
  alumnoId?: Prisma.StringFieldUpdateOperationsInput | string
  examenGeneradoId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  folio?: Prisma.StringFieldUpdateOperationsInput | string
  numeroPregunta?: Prisma.IntFieldUpdateOperationsInput | number
  comentario?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  solicitadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  atendidoEn?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  respuestaDocente?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  firmaDocente?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  firmadoEn?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  cerradoEn?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  conformidadAlumno?: Prisma.BoolFieldUpdateOperationsInput | boolean
  conformidadActualizadaEn?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  origen?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SolicitudRevisionCreateManyInput = {
  id?: string
  externoId: string
  periodoId: string
  docenteId: string
  alumnoId: string
  examenGeneradoId?: string | null
  folio: string
  numeroPregunta: number
  comentario?: string | null
  estado?: string
  solicitadoEn: Date | string
  atendidoEn?: Date | string | null
  respuestaDocente?: string | null
  firmaDocente?: string | null
  firmadoEn?: Date | string | null
  cerradoEn?: Date | string | null
  conformidadAlumno?: boolean
  conformidadActualizadaEn?: Date | string | null
  origen?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SolicitudRevisionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  externoId?: Prisma.StringFieldUpdateOperationsInput | string
  periodoId?: Prisma.StringFieldUpdateOperationsInput | string
  docenteId?: Prisma.StringFieldUpdateOperationsInput | string
  alumnoId?: Prisma.StringFieldUpdateOperationsInput | string
  examenGeneradoId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  folio?: Prisma.StringFieldUpdateOperationsInput | string
  numeroPregunta?: Prisma.IntFieldUpdateOperationsInput | number
  comentario?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  solicitadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  atendidoEn?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  respuestaDocente?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  firmaDocente?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  firmadoEn?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  cerradoEn?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  conformidadAlumno?: Prisma.BoolFieldUpdateOperationsInput | boolean
  conformidadActualizadaEn?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  origen?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SolicitudRevisionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  externoId?: Prisma.StringFieldUpdateOperationsInput | string
  periodoId?: Prisma.StringFieldUpdateOperationsInput | string
  docenteId?: Prisma.StringFieldUpdateOperationsInput | string
  alumnoId?: Prisma.StringFieldUpdateOperationsInput | string
  examenGeneradoId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  folio?: Prisma.StringFieldUpdateOperationsInput | string
  numeroPregunta?: Prisma.IntFieldUpdateOperationsInput | number
  comentario?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  solicitadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  atendidoEn?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  respuestaDocente?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  firmaDocente?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  firmadoEn?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  cerradoEn?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  conformidadAlumno?: Prisma.BoolFieldUpdateOperationsInput | boolean
  conformidadActualizadaEn?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  origen?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SolicitudRevisionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  externoId?: Prisma.SortOrder
  periodoId?: Prisma.SortOrder
  docenteId?: Prisma.SortOrder
  alumnoId?: Prisma.SortOrder
  examenGeneradoId?: Prisma.SortOrder
  folio?: Prisma.SortOrder
  numeroPregunta?: Prisma.SortOrder
  comentario?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  solicitadoEn?: Prisma.SortOrder
  atendidoEn?: Prisma.SortOrder
  respuestaDocente?: Prisma.SortOrder
  firmaDocente?: Prisma.SortOrder
  firmadoEn?: Prisma.SortOrder
  cerradoEn?: Prisma.SortOrder
  conformidadAlumno?: Prisma.SortOrder
  conformidadActualizadaEn?: Prisma.SortOrder
  origen?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SolicitudRevisionAvgOrderByAggregateInput = {
  numeroPregunta?: Prisma.SortOrder
}

export type SolicitudRevisionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  externoId?: Prisma.SortOrder
  periodoId?: Prisma.SortOrder
  docenteId?: Prisma.SortOrder
  alumnoId?: Prisma.SortOrder
  examenGeneradoId?: Prisma.SortOrder
  folio?: Prisma.SortOrder
  numeroPregunta?: Prisma.SortOrder
  comentario?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  solicitadoEn?: Prisma.SortOrder
  atendidoEn?: Prisma.SortOrder
  respuestaDocente?: Prisma.SortOrder
  firmaDocente?: Prisma.SortOrder
  firmadoEn?: Prisma.SortOrder
  cerradoEn?: Prisma.SortOrder
  conformidadAlumno?: Prisma.SortOrder
  conformidadActualizadaEn?: Prisma.SortOrder
  origen?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SolicitudRevisionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  externoId?: Prisma.SortOrder
  periodoId?: Prisma.SortOrder
  docenteId?: Prisma.SortOrder
  alumnoId?: Prisma.SortOrder
  examenGeneradoId?: Prisma.SortOrder
  folio?: Prisma.SortOrder
  numeroPregunta?: Prisma.SortOrder
  comentario?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  solicitadoEn?: Prisma.SortOrder
  atendidoEn?: Prisma.SortOrder
  respuestaDocente?: Prisma.SortOrder
  firmaDocente?: Prisma.SortOrder
  firmadoEn?: Prisma.SortOrder
  cerradoEn?: Prisma.SortOrder
  conformidadAlumno?: Prisma.SortOrder
  conformidadActualizadaEn?: Prisma.SortOrder
  origen?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SolicitudRevisionSumOrderByAggregateInput = {
  numeroPregunta?: Prisma.SortOrder
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}



export type SolicitudRevisionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  externoId?: boolean
  periodoId?: boolean
  docenteId?: boolean
  alumnoId?: boolean
  examenGeneradoId?: boolean
  folio?: boolean
  numeroPregunta?: boolean
  comentario?: boolean
  estado?: boolean
  solicitadoEn?: boolean
  atendidoEn?: boolean
  respuestaDocente?: boolean
  firmaDocente?: boolean
  firmadoEn?: boolean
  cerradoEn?: boolean
  conformidadAlumno?: boolean
  conformidadActualizadaEn?: boolean
  origen?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["solicitudRevision"]>

export type SolicitudRevisionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  externoId?: boolean
  periodoId?: boolean
  docenteId?: boolean
  alumnoId?: boolean
  examenGeneradoId?: boolean
  folio?: boolean
  numeroPregunta?: boolean
  comentario?: boolean
  estado?: boolean
  solicitadoEn?: boolean
  atendidoEn?: boolean
  respuestaDocente?: boolean
  firmaDocente?: boolean
  firmadoEn?: boolean
  cerradoEn?: boolean
  conformidadAlumno?: boolean
  conformidadActualizadaEn?: boolean
  origen?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["solicitudRevision"]>

export type SolicitudRevisionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  externoId?: boolean
  periodoId?: boolean
  docenteId?: boolean
  alumnoId?: boolean
  examenGeneradoId?: boolean
  folio?: boolean
  numeroPregunta?: boolean
  comentario?: boolean
  estado?: boolean
  solicitadoEn?: boolean
  atendidoEn?: boolean
  respuestaDocente?: boolean
  firmaDocente?: boolean
  firmadoEn?: boolean
  cerradoEn?: boolean
  conformidadAlumno?: boolean
  conformidadActualizadaEn?: boolean
  origen?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["solicitudRevision"]>

export type SolicitudRevisionSelectScalar = {
  id?: boolean
  externoId?: boolean
  periodoId?: boolean
  docenteId?: boolean
  alumnoId?: boolean
  examenGeneradoId?: boolean
  folio?: boolean
  numeroPregunta?: boolean
  comentario?: boolean
  estado?: boolean
  solicitadoEn?: boolean
  atendidoEn?: boolean
  respuestaDocente?: boolean
  firmaDocente?: boolean
  firmadoEn?: boolean
  cerradoEn?: boolean
  conformidadAlumno?: boolean
  conformidadActualizadaEn?: boolean
  origen?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type SolicitudRevisionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "externoId" | "periodoId" | "docenteId" | "alumnoId" | "examenGeneradoId" | "folio" | "numeroPregunta" | "comentario" | "estado" | "solicitadoEn" | "atendidoEn" | "respuestaDocente" | "firmaDocente" | "firmadoEn" | "cerradoEn" | "conformidadAlumno" | "conformidadActualizadaEn" | "origen" | "createdAt" | "updatedAt", ExtArgs["result"]["solicitudRevision"]>

export type $SolicitudRevisionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SolicitudRevision"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    externoId: string
    periodoId: string
    docenteId: string
    alumnoId: string
    examenGeneradoId: string | null
    folio: string
    numeroPregunta: number
    comentario: string | null
    estado: string
    solicitadoEn: Date
    atendidoEn: Date | null
    respuestaDocente: string | null
    firmaDocente: string | null
    firmadoEn: Date | null
    cerradoEn: Date | null
    conformidadAlumno: boolean
    conformidadActualizadaEn: Date | null
    origen: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["solicitudRevision"]>
  composites: {}
}

export type SolicitudRevisionGetPayload<S extends boolean | null | undefined | SolicitudRevisionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SolicitudRevisionPayload, S>

export type SolicitudRevisionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SolicitudRevisionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SolicitudRevisionCountAggregateInputType | true
  }

export interface SolicitudRevisionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SolicitudRevision'], meta: { name: 'SolicitudRevision' } }
  /**
   * Find zero or one SolicitudRevision that matches the filter.
   * @param {SolicitudRevisionFindUniqueArgs} args - Arguments to find a SolicitudRevision
   * @example
   * // Get one SolicitudRevision
   * const solicitudRevision = await prisma.solicitudRevision.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SolicitudRevisionFindUniqueArgs>(args: Prisma.SelectSubset<T, SolicitudRevisionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SolicitudRevisionClient<runtime.Types.Result.GetResult<Prisma.$SolicitudRevisionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SolicitudRevision that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SolicitudRevisionFindUniqueOrThrowArgs} args - Arguments to find a SolicitudRevision
   * @example
   * // Get one SolicitudRevision
   * const solicitudRevision = await prisma.solicitudRevision.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SolicitudRevisionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SolicitudRevisionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SolicitudRevisionClient<runtime.Types.Result.GetResult<Prisma.$SolicitudRevisionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SolicitudRevision that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SolicitudRevisionFindFirstArgs} args - Arguments to find a SolicitudRevision
   * @example
   * // Get one SolicitudRevision
   * const solicitudRevision = await prisma.solicitudRevision.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SolicitudRevisionFindFirstArgs>(args?: Prisma.SelectSubset<T, SolicitudRevisionFindFirstArgs<ExtArgs>>): Prisma.Prisma__SolicitudRevisionClient<runtime.Types.Result.GetResult<Prisma.$SolicitudRevisionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SolicitudRevision that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SolicitudRevisionFindFirstOrThrowArgs} args - Arguments to find a SolicitudRevision
   * @example
   * // Get one SolicitudRevision
   * const solicitudRevision = await prisma.solicitudRevision.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SolicitudRevisionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SolicitudRevisionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SolicitudRevisionClient<runtime.Types.Result.GetResult<Prisma.$SolicitudRevisionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SolicitudRevisions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SolicitudRevisionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SolicitudRevisions
   * const solicitudRevisions = await prisma.solicitudRevision.findMany()
   * 
   * // Get first 10 SolicitudRevisions
   * const solicitudRevisions = await prisma.solicitudRevision.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const solicitudRevisionWithIdOnly = await prisma.solicitudRevision.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SolicitudRevisionFindManyArgs>(args?: Prisma.SelectSubset<T, SolicitudRevisionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SolicitudRevisionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SolicitudRevision.
   * @param {SolicitudRevisionCreateArgs} args - Arguments to create a SolicitudRevision.
   * @example
   * // Create one SolicitudRevision
   * const SolicitudRevision = await prisma.solicitudRevision.create({
   *   data: {
   *     // ... data to create a SolicitudRevision
   *   }
   * })
   * 
   */
  create<T extends SolicitudRevisionCreateArgs>(args: Prisma.SelectSubset<T, SolicitudRevisionCreateArgs<ExtArgs>>): Prisma.Prisma__SolicitudRevisionClient<runtime.Types.Result.GetResult<Prisma.$SolicitudRevisionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SolicitudRevisions.
   * @param {SolicitudRevisionCreateManyArgs} args - Arguments to create many SolicitudRevisions.
   * @example
   * // Create many SolicitudRevisions
   * const solicitudRevision = await prisma.solicitudRevision.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SolicitudRevisionCreateManyArgs>(args?: Prisma.SelectSubset<T, SolicitudRevisionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SolicitudRevisions and returns the data saved in the database.
   * @param {SolicitudRevisionCreateManyAndReturnArgs} args - Arguments to create many SolicitudRevisions.
   * @example
   * // Create many SolicitudRevisions
   * const solicitudRevision = await prisma.solicitudRevision.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SolicitudRevisions and only return the `id`
   * const solicitudRevisionWithIdOnly = await prisma.solicitudRevision.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SolicitudRevisionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SolicitudRevisionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SolicitudRevisionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SolicitudRevision.
   * @param {SolicitudRevisionDeleteArgs} args - Arguments to delete one SolicitudRevision.
   * @example
   * // Delete one SolicitudRevision
   * const SolicitudRevision = await prisma.solicitudRevision.delete({
   *   where: {
   *     // ... filter to delete one SolicitudRevision
   *   }
   * })
   * 
   */
  delete<T extends SolicitudRevisionDeleteArgs>(args: Prisma.SelectSubset<T, SolicitudRevisionDeleteArgs<ExtArgs>>): Prisma.Prisma__SolicitudRevisionClient<runtime.Types.Result.GetResult<Prisma.$SolicitudRevisionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SolicitudRevision.
   * @param {SolicitudRevisionUpdateArgs} args - Arguments to update one SolicitudRevision.
   * @example
   * // Update one SolicitudRevision
   * const solicitudRevision = await prisma.solicitudRevision.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SolicitudRevisionUpdateArgs>(args: Prisma.SelectSubset<T, SolicitudRevisionUpdateArgs<ExtArgs>>): Prisma.Prisma__SolicitudRevisionClient<runtime.Types.Result.GetResult<Prisma.$SolicitudRevisionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SolicitudRevisions.
   * @param {SolicitudRevisionDeleteManyArgs} args - Arguments to filter SolicitudRevisions to delete.
   * @example
   * // Delete a few SolicitudRevisions
   * const { count } = await prisma.solicitudRevision.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SolicitudRevisionDeleteManyArgs>(args?: Prisma.SelectSubset<T, SolicitudRevisionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SolicitudRevisions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SolicitudRevisionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SolicitudRevisions
   * const solicitudRevision = await prisma.solicitudRevision.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SolicitudRevisionUpdateManyArgs>(args: Prisma.SelectSubset<T, SolicitudRevisionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SolicitudRevisions and returns the data updated in the database.
   * @param {SolicitudRevisionUpdateManyAndReturnArgs} args - Arguments to update many SolicitudRevisions.
   * @example
   * // Update many SolicitudRevisions
   * const solicitudRevision = await prisma.solicitudRevision.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SolicitudRevisions and only return the `id`
   * const solicitudRevisionWithIdOnly = await prisma.solicitudRevision.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SolicitudRevisionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SolicitudRevisionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SolicitudRevisionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SolicitudRevision.
   * @param {SolicitudRevisionUpsertArgs} args - Arguments to update or create a SolicitudRevision.
   * @example
   * // Update or create a SolicitudRevision
   * const solicitudRevision = await prisma.solicitudRevision.upsert({
   *   create: {
   *     // ... data to create a SolicitudRevision
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SolicitudRevision we want to update
   *   }
   * })
   */
  upsert<T extends SolicitudRevisionUpsertArgs>(args: Prisma.SelectSubset<T, SolicitudRevisionUpsertArgs<ExtArgs>>): Prisma.Prisma__SolicitudRevisionClient<runtime.Types.Result.GetResult<Prisma.$SolicitudRevisionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SolicitudRevisions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SolicitudRevisionCountArgs} args - Arguments to filter SolicitudRevisions to count.
   * @example
   * // Count the number of SolicitudRevisions
   * const count = await prisma.solicitudRevision.count({
   *   where: {
   *     // ... the filter for the SolicitudRevisions we want to count
   *   }
   * })
  **/
  count<T extends SolicitudRevisionCountArgs>(
    args?: Prisma.Subset<T, SolicitudRevisionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SolicitudRevisionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SolicitudRevision.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SolicitudRevisionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SolicitudRevisionAggregateArgs>(args: Prisma.Subset<T, SolicitudRevisionAggregateArgs>): Prisma.PrismaPromise<GetSolicitudRevisionAggregateType<T>>

  /**
   * Group by SolicitudRevision.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SolicitudRevisionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SolicitudRevisionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SolicitudRevisionGroupByArgs['orderBy'] }
      : { orderBy?: SolicitudRevisionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SolicitudRevisionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSolicitudRevisionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SolicitudRevision model
 */
readonly fields: SolicitudRevisionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SolicitudRevision.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SolicitudRevisionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SolicitudRevision model
 */
export interface SolicitudRevisionFieldRefs {
  readonly id: Prisma.FieldRef<"SolicitudRevision", 'String'>
  readonly externoId: Prisma.FieldRef<"SolicitudRevision", 'String'>
  readonly periodoId: Prisma.FieldRef<"SolicitudRevision", 'String'>
  readonly docenteId: Prisma.FieldRef<"SolicitudRevision", 'String'>
  readonly alumnoId: Prisma.FieldRef<"SolicitudRevision", 'String'>
  readonly examenGeneradoId: Prisma.FieldRef<"SolicitudRevision", 'String'>
  readonly folio: Prisma.FieldRef<"SolicitudRevision", 'String'>
  readonly numeroPregunta: Prisma.FieldRef<"SolicitudRevision", 'Int'>
  readonly comentario: Prisma.FieldRef<"SolicitudRevision", 'String'>
  readonly estado: Prisma.FieldRef<"SolicitudRevision", 'String'>
  readonly solicitadoEn: Prisma.FieldRef<"SolicitudRevision", 'DateTime'>
  readonly atendidoEn: Prisma.FieldRef<"SolicitudRevision", 'DateTime'>
  readonly respuestaDocente: Prisma.FieldRef<"SolicitudRevision", 'String'>
  readonly firmaDocente: Prisma.FieldRef<"SolicitudRevision", 'String'>
  readonly firmadoEn: Prisma.FieldRef<"SolicitudRevision", 'DateTime'>
  readonly cerradoEn: Prisma.FieldRef<"SolicitudRevision", 'DateTime'>
  readonly conformidadAlumno: Prisma.FieldRef<"SolicitudRevision", 'Boolean'>
  readonly conformidadActualizadaEn: Prisma.FieldRef<"SolicitudRevision", 'DateTime'>
  readonly origen: Prisma.FieldRef<"SolicitudRevision", 'String'>
  readonly createdAt: Prisma.FieldRef<"SolicitudRevision", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"SolicitudRevision", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SolicitudRevision findUnique
 */
export type SolicitudRevisionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SolicitudRevision
   */
  select?: Prisma.SolicitudRevisionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SolicitudRevision
   */
  omit?: Prisma.SolicitudRevisionOmit<ExtArgs> | null
  /**
   * Filter, which SolicitudRevision to fetch.
   */
  where: Prisma.SolicitudRevisionWhereUniqueInput
}

/**
 * SolicitudRevision findUniqueOrThrow
 */
export type SolicitudRevisionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SolicitudRevision
   */
  select?: Prisma.SolicitudRevisionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SolicitudRevision
   */
  omit?: Prisma.SolicitudRevisionOmit<ExtArgs> | null
  /**
   * Filter, which SolicitudRevision to fetch.
   */
  where: Prisma.SolicitudRevisionWhereUniqueInput
}

/**
 * SolicitudRevision findFirst
 */
export type SolicitudRevisionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SolicitudRevision
   */
  select?: Prisma.SolicitudRevisionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SolicitudRevision
   */
  omit?: Prisma.SolicitudRevisionOmit<ExtArgs> | null
  /**
   * Filter, which SolicitudRevision to fetch.
   */
  where?: Prisma.SolicitudRevisionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SolicitudRevisions to fetch.
   */
  orderBy?: Prisma.SolicitudRevisionOrderByWithRelationInput | Prisma.SolicitudRevisionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SolicitudRevisions.
   */
  cursor?: Prisma.SolicitudRevisionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SolicitudRevisions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SolicitudRevisions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SolicitudRevisions.
   */
  distinct?: Prisma.SolicitudRevisionScalarFieldEnum | Prisma.SolicitudRevisionScalarFieldEnum[]
}

/**
 * SolicitudRevision findFirstOrThrow
 */
export type SolicitudRevisionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SolicitudRevision
   */
  select?: Prisma.SolicitudRevisionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SolicitudRevision
   */
  omit?: Prisma.SolicitudRevisionOmit<ExtArgs> | null
  /**
   * Filter, which SolicitudRevision to fetch.
   */
  where?: Prisma.SolicitudRevisionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SolicitudRevisions to fetch.
   */
  orderBy?: Prisma.SolicitudRevisionOrderByWithRelationInput | Prisma.SolicitudRevisionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SolicitudRevisions.
   */
  cursor?: Prisma.SolicitudRevisionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SolicitudRevisions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SolicitudRevisions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SolicitudRevisions.
   */
  distinct?: Prisma.SolicitudRevisionScalarFieldEnum | Prisma.SolicitudRevisionScalarFieldEnum[]
}

/**
 * SolicitudRevision findMany
 */
export type SolicitudRevisionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SolicitudRevision
   */
  select?: Prisma.SolicitudRevisionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SolicitudRevision
   */
  omit?: Prisma.SolicitudRevisionOmit<ExtArgs> | null
  /**
   * Filter, which SolicitudRevisions to fetch.
   */
  where?: Prisma.SolicitudRevisionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SolicitudRevisions to fetch.
   */
  orderBy?: Prisma.SolicitudRevisionOrderByWithRelationInput | Prisma.SolicitudRevisionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SolicitudRevisions.
   */
  cursor?: Prisma.SolicitudRevisionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SolicitudRevisions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SolicitudRevisions.
   */
  skip?: number
  distinct?: Prisma.SolicitudRevisionScalarFieldEnum | Prisma.SolicitudRevisionScalarFieldEnum[]
}

/**
 * SolicitudRevision create
 */
export type SolicitudRevisionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SolicitudRevision
   */
  select?: Prisma.SolicitudRevisionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SolicitudRevision
   */
  omit?: Prisma.SolicitudRevisionOmit<ExtArgs> | null
  /**
   * The data needed to create a SolicitudRevision.
   */
  data: Prisma.XOR<Prisma.SolicitudRevisionCreateInput, Prisma.SolicitudRevisionUncheckedCreateInput>
}

/**
 * SolicitudRevision createMany
 */
export type SolicitudRevisionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SolicitudRevisions.
   */
  data: Prisma.SolicitudRevisionCreateManyInput | Prisma.SolicitudRevisionCreateManyInput[]
}

/**
 * SolicitudRevision createManyAndReturn
 */
export type SolicitudRevisionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SolicitudRevision
   */
  select?: Prisma.SolicitudRevisionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SolicitudRevision
   */
  omit?: Prisma.SolicitudRevisionOmit<ExtArgs> | null
  /**
   * The data used to create many SolicitudRevisions.
   */
  data: Prisma.SolicitudRevisionCreateManyInput | Prisma.SolicitudRevisionCreateManyInput[]
}

/**
 * SolicitudRevision update
 */
export type SolicitudRevisionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SolicitudRevision
   */
  select?: Prisma.SolicitudRevisionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SolicitudRevision
   */
  omit?: Prisma.SolicitudRevisionOmit<ExtArgs> | null
  /**
   * The data needed to update a SolicitudRevision.
   */
  data: Prisma.XOR<Prisma.SolicitudRevisionUpdateInput, Prisma.SolicitudRevisionUncheckedUpdateInput>
  /**
   * Choose, which SolicitudRevision to update.
   */
  where: Prisma.SolicitudRevisionWhereUniqueInput
}

/**
 * SolicitudRevision updateMany
 */
export type SolicitudRevisionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SolicitudRevisions.
   */
  data: Prisma.XOR<Prisma.SolicitudRevisionUpdateManyMutationInput, Prisma.SolicitudRevisionUncheckedUpdateManyInput>
  /**
   * Filter which SolicitudRevisions to update
   */
  where?: Prisma.SolicitudRevisionWhereInput
  /**
   * Limit how many SolicitudRevisions to update.
   */
  limit?: number
}

/**
 * SolicitudRevision updateManyAndReturn
 */
export type SolicitudRevisionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SolicitudRevision
   */
  select?: Prisma.SolicitudRevisionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SolicitudRevision
   */
  omit?: Prisma.SolicitudRevisionOmit<ExtArgs> | null
  /**
   * The data used to update SolicitudRevisions.
   */
  data: Prisma.XOR<Prisma.SolicitudRevisionUpdateManyMutationInput, Prisma.SolicitudRevisionUncheckedUpdateManyInput>
  /**
   * Filter which SolicitudRevisions to update
   */
  where?: Prisma.SolicitudRevisionWhereInput
  /**
   * Limit how many SolicitudRevisions to update.
   */
  limit?: number
}

/**
 * SolicitudRevision upsert
 */
export type SolicitudRevisionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SolicitudRevision
   */
  select?: Prisma.SolicitudRevisionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SolicitudRevision
   */
  omit?: Prisma.SolicitudRevisionOmit<ExtArgs> | null
  /**
   * The filter to search for the SolicitudRevision to update in case it exists.
   */
  where: Prisma.SolicitudRevisionWhereUniqueInput
  /**
   * In case the SolicitudRevision found by the `where` argument doesn't exist, create a new SolicitudRevision with this data.
   */
  create: Prisma.XOR<Prisma.SolicitudRevisionCreateInput, Prisma.SolicitudRevisionUncheckedCreateInput>
  /**
   * In case the SolicitudRevision was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SolicitudRevisionUpdateInput, Prisma.SolicitudRevisionUncheckedUpdateInput>
}

/**
 * SolicitudRevision delete
 */
export type SolicitudRevisionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SolicitudRevision
   */
  select?: Prisma.SolicitudRevisionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SolicitudRevision
   */
  omit?: Prisma.SolicitudRevisionOmit<ExtArgs> | null
  /**
   * Filter which SolicitudRevision to delete.
   */
  where: Prisma.SolicitudRevisionWhereUniqueInput
}

/**
 * SolicitudRevision deleteMany
 */
export type SolicitudRevisionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SolicitudRevisions to delete
   */
  where?: Prisma.SolicitudRevisionWhereInput
  /**
   * Limit how many SolicitudRevisions to delete.
   */
  limit?: number
}

/**
 * SolicitudRevision without action
 */
export type SolicitudRevisionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SolicitudRevision
   */
  select?: Prisma.SolicitudRevisionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SolicitudRevision
   */
  omit?: Prisma.SolicitudRevisionOmit<ExtArgs> | null
}
